from typing import override, Union

from .genVec2 import genVec2
from .bvec3 import bvec3
from .bvec4 import bvec4


class bvec2(genVec2):

    @property
    def x(self)->bool: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->bool: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->bvec2: ...

    @property
    def xy(self)->bvec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->bvec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->bvec2: ...

    @property
    def xxx(self)->bvec3: ...

    @property
    def xxy(self)->bvec3: ...

    @property
    def xyx(self)->bvec3: ...

    @property
    def xyy(self)->bvec3: ...

    @property
    def yxx(self)->bvec3: ...

    @property
    def yxy(self)->bvec3: ...

    @property
    def yyx(self)->bvec3: ...

    @property
    def yyy(self)->bvec3: ...

    @property
    def xxxx(self)->bvec4: ...

    @property
    def xxxy(self)->bvec4: ...

    @property
    def xxyx(self)->bvec4: ...

    @property
    def xxyy(self)->bvec4: ...

    @property
    def xyxx(self)->bvec4: ...

    @property
    def xyxy(self)->bvec4: ...

    @property
    def xyyx(self)->bvec4: ...

    @property
    def xyyy(self)->bvec4: ...

    @property
    def yxxx(self)->bvec4: ...

    @property
    def yxxy(self)->bvec4: ...

    @property
    def yxyx(self)->bvec4: ...

    @property
    def yxyy(self)->bvec4: ...

    @property
    def yyxx(self)->bvec4: ...

    @property
    def yyxy(self)->bvec4: ...

    @property
    def yyyx(self)->bvec4: ...

    @property
    def yyyy(self)->bvec4: ...

    @property
    def r(self)->bool: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->bool: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->bvec2: ...

    @property
    def rg(self)->bvec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->bvec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->bvec2: ...

    @property
    def rrr(self)->bvec3: ...

    @property
    def rrg(self)->bvec3: ...

    @property
    def rgr(self)->bvec3: ...

    @property
    def rgg(self)->bvec3: ...

    @property
    def grr(self)->bvec3: ...

    @property
    def grg(self)->bvec3: ...

    @property
    def ggr(self)->bvec3: ...

    @property
    def ggg(self)->bvec3: ...

    @property
    def rrrr(self)->bvec4: ...

    @property
    def rrrg(self)->bvec4: ...

    @property
    def rrgr(self)->bvec4: ...

    @property
    def rrgg(self)->bvec4: ...

    @property
    def rgrr(self)->bvec4: ...

    @property
    def rgrg(self)->bvec4: ...

    @property
    def rggr(self)->bvec4: ...

    @property
    def rggg(self)->bvec4: ...

    @property
    def grrr(self)->bvec4: ...

    @property
    def grrg(self)->bvec4: ...

    @property
    def grgr(self)->bvec4: ...

    @property
    def grgg(self)->bvec4: ...

    @property
    def ggrr(self)->bvec4: ...

    @property
    def ggrg(self)->bvec4: ...

    @property
    def gggr(self)->bvec4: ...

    @property
    def gggg(self)->bvec4: ...

    @property
    def s(self)->bool: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->bool: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def ss(self)->bvec2: ...

    @property
    def st(self)->bvec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ts(self)->bvec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tt(self)->bvec2: ...

    @property
    def sss(self)->bvec3: ...

    @property
    def sst(self)->bvec3: ...

    @property
    def sts(self)->bvec3: ...

    @property
    def stt(self)->bvec3: ...

    @property
    def tss(self)->bvec3: ...

    @property
    def tst(self)->bvec3: ...

    @property
    def tts(self)->bvec3: ...

    @property
    def ttt(self)->bvec3: ...

    @property
    def ssss(self)->bvec4: ...

    @property
    def ssst(self)->bvec4: ...

    @property
    def ssts(self)->bvec4: ...

    @property
    def sstt(self)->bvec4: ...

    @property
    def stss(self)->bvec4: ...

    @property
    def stst(self)->bvec4: ...

    @property
    def stts(self)->bvec4: ...

    @property
    def sttt(self)->bvec4: ...

    @property
    def tsss(self)->bvec4: ...

    @property
    def tsst(self)->bvec4: ...

    @property
    def tsts(self)->bvec4: ...

    @property
    def tstt(self)->bvec4: ...

    @property
    def ttss(self)->bvec4: ...

    @property
    def ttst(self)->bvec4: ...

    @property
    def ttts(self)->bvec4: ...

    @property
    def tttt(self)->bvec4: ...
