
    @property
    def z(self)->float: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def grbb(self)->dvec4: ...

    @property
    def zxyz(self)->dvec4: ...

    @property
    def rrgr(self)->dvec4: ...

    @property
    def tt(self)->dvec2: ...

    @property
    def xzyy(self)->dvec4: ...

    @property
    def ttps(self)->dvec4: ...

    @property
    def rgbb(self)->dvec4: ...

    @property
    def zyzz(self)->dvec4: ...

    @property
    def t(self)->float: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def gbgr(self)->dvec4: ...

    @property
    def xxz(self)->dvec3: ...

    @property
    def gbrg(self)->dvec4: ...

    @property
    def zxx(self)->dvec3: ...

    @property
    def yyyx(self)->dvec4: ...

    @property
    def gbbg(self)->dvec4: ...

    @property
    def tsss(self)->dvec4: ...

    @property
    def zzyy(self)->dvec4: ...

    @property
    def bbbr(self)->dvec4: ...

    @property
    def stpt(self)->dvec4: ...

    @property
    def yxy(self)->dvec3: ...

    @property
    def tttp(self)->dvec4: ...

    @property
    def bggg(self)->dvec4: ...

    @property
    def tttt(self)->dvec4: ...

    @property
    def gg(self)->dvec2: ...

    @property
    def ggbb(self)->dvec4: ...

    @property
    def brb(self)->dvec3: ...

    @property
    def zyxz(self)->dvec4: ...

    @property
    def zxxx(self)->dvec4: ...

    @property
    def xxzz(self)->dvec4: ...

    @property
    def yxzx(self)->dvec4: ...

    @property
    def yxzy(self)->dvec4: ...

    @property
    def zzzz(self)->dvec4: ...

    @property
    def ptts(self)->dvec4: ...

    @property
    def zxxz(self)->dvec4: ...

    @property
    def psp(self)->dvec3: ...

    @property
    def rrr(self)->dvec3: ...

    @property
    def bbg(self)->dvec3: ...

    @property
    def ttsp(self)->dvec4: ...

    @property
    def zzzx(self)->dvec4: ...

    @property
    def brg(self)->dvec3: ...

    @brg.setter
    def brg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbbr(self)->dvec4: ...

    @property
    def tstp(self)->dvec4: ...

    @property
    def brgr(self)->dvec4: ...

    @property
    def yzyx(self)->dvec4: ...

    @property
    def xyxx(self)->dvec4: ...

    @property
    def rbb(self)->dvec3: ...

    @property
    def ps(self)->dvec2: ...

    @ps.setter
    def ps(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def sppp(self)->dvec4: ...

    @property
    def rrrg(self)->dvec4: ...

    @property
    def rgrg(self)->dvec4: ...

    @property
    def yzz(self)->dvec3: ...

    @property
    def bbrr(self)->dvec4: ...

    @property
    def rbbb(self)->dvec4: ...

    @property
    def xyz(self)->dvec3: ...

    @xyz.setter
    def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def pptt(self)->dvec4: ...

    @property
    def ppp(self)->dvec3: ...

    @property
    def zzyz(self)->dvec4: ...

    @property
    def bbr(self)->dvec3: ...

    @property
    def xyy(self)->dvec3: ...

    @property
    def tsp(self)->dvec3: ...

    @tsp.setter
    def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyx(self)->dvec3: ...

    @zyx.setter
    def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xx(self)->dvec2: ...

    @property
    def pppp(self)->dvec4: ...

    @property
    def gbrb(self)->dvec4: ...

    @property
    def sssp(self)->dvec4: ...

    @property
    def pttp(self)->dvec4: ...

    @property
    def ptt(self)->dvec3: ...

    @property
    def zx(self)->dvec2: ...

    @zx.setter
    def zx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zz(self)->dvec2: ...

    @property
    def xzx(self)->dvec3: ...

    @property
    def spt(self)->dvec3: ...

    @spt.setter
    def spt(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gggg(self)->dvec4: ...

    @property
    def tst(self)->dvec3: ...

    @property
    def stss(self)->dvec4: ...

    @property
    def xy(self)->dvec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rr(self)->dvec2: ...

    @property
    def yyxz(self)->dvec4: ...

    @property
    def zzxz(self)->dvec4: ...

    @property
    def yxz(self)->dvec3: ...

    @yxz.setter
    def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ttst(self)->dvec4: ...

    @property
    def yxyz(self)->dvec4: ...

    @property
    def rbr(self)->dvec3: ...

    @property
    def tsts(self)->dvec4: ...

    @property
    def yz(self)->dvec2: ...

    @yz.setter
    def yz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ptpp(self)->dvec4: ...

    @property
    def zyyz(self)->dvec4: ...

    @property
    def pttt(self)->dvec4: ...

    @property
    def xzy(self)->dvec3: ...

    @xzy.setter
    def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def pptp(self)->dvec4: ...

    @property
    def xxxz(self)->dvec4: ...

    @property
    def rrrb(self)->dvec4: ...

    @property
    def ppst(self)->dvec4: ...

    @property
    def xyzy(self)->dvec4: ...

    @property
    def gb(self)->dvec2: ...

    @gb.setter
    def gb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bbbg(self)->dvec4: ...

    @property
    def pstp(self)->dvec4: ...

    @property
    def grrg(self)->dvec4: ...

    @property
    def rgrr(self)->dvec4: ...

    @property
    def zxyy(self)->dvec4: ...

    @property
    def brrb(self)->dvec4: ...

    @property
    def pt(self)->dvec2: ...

    @pt.setter
    def pt(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rbrg(self)->dvec4: ...

    @property
    def xyzz(self)->dvec4: ...

    @property
    def pst(self)->dvec3: ...

    @pst.setter
    def pst(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ggg(self)->dvec3: ...

    @property
    def bgrr(self)->dvec4: ...

    @property
    def tpps(self)->dvec4: ...

    @property
    def tsst(self)->dvec4: ...

    @property
    def pts(self)->dvec3: ...

    @pts.setter
    def pts(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zxyx(self)->dvec4: ...

    @property
    def yyzx(self)->dvec4: ...

    @property
    def tssp(self)->dvec4: ...

    @property
    def rbrr(self)->dvec4: ...

    @property
    def yyyz(self)->dvec4: ...

    @property
    def stst(self)->dvec4: ...

    @property
    def pssp(self)->dvec4: ...

    @property
    def rrgg(self)->dvec4: ...

    @property
    def b(self)->float: ...

    @b.setter
    def b(self, value:Union[bool, int, float])->None: ...

    @property
    def brbb(self)->dvec4: ...

    @property
    def tsps(self)->dvec4: ...

    @property
    def rgb(self)->dvec3: ...

    @rgb.setter
    def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgrg(self)->dvec4: ...

    @property
    def xzz(self)->dvec3: ...

    @property
    def rb(self)->dvec2: ...

    @rb.setter
    def rb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def stpp(self)->dvec4: ...

    @property
    def grrb(self)->dvec4: ...

    @property
    def yzzz(self)->dvec4: ...

    @property
    def xxxx(self)->dvec4: ...

    @property
    def yyzy(self)->dvec4: ...

    @property
    def grbr(self)->dvec4: ...

    @property
    def gggb(self)->dvec4: ...

    @property
    def grbg(self)->dvec4: ...

    @property
    def rgr(self)->dvec3: ...

    @property
    def xzxz(self)->dvec4: ...

    @property
    def rbgg(self)->dvec4: ...

    @property
    def zyz(self)->dvec3: ...

    @property
    def grgg(self)->dvec4: ...

    @property
    def sstp(self)->dvec4: ...

    @property
    def bbgr(self)->dvec4: ...

    @property
    def rbg(self)->dvec3: ...

    @rbg.setter
    def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gbgb(self)->dvec4: ...

    @property
    def xxxy(self)->dvec4: ...

    @property
    def xzxy(self)->dvec4: ...

    @property
    def zyyy(self)->dvec4: ...

    @property
    def psss(self)->dvec4: ...

    @property
    def rrg(self)->dvec3: ...

    @property
    def ggbr(self)->dvec4: ...

    @property
    def ptst(self)->dvec4: ...

    @property
    def stts(self)->dvec4: ...

    @property
    def psts(self)->dvec4: ...

    @property
    def rgg(self)->dvec3: ...

    @property
    def rbbg(self)->dvec4: ...

    @property
    def gbg(self)->dvec3: ...

    @property
    def tpt(self)->dvec3: ...

    @property
    def ppss(self)->dvec4: ...

    @property
    def rg(self)->dvec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rggr(self)->dvec4: ...

    @property
    def xxx(self)->dvec3: ...

    @property
    def sstt(self)->dvec4: ...

    @property
    def br(self)->dvec2: ...

    @br.setter
    def br(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def spps(self)->dvec4: ...

    @property
    def yxx(self)->dvec3: ...

    @property
    def ssst(self)->dvec4: ...

    @property
    def xyx(self)->dvec3: ...

    @property
    def bbbb(self)->dvec4: ...

    @property
    def zzxy(self)->dvec4: ...

    @property
    def bgg(self)->dvec3: ...

    @property
    def yyzz(self)->dvec4: ...

    @property
    def grb(self)->dvec3: ...

    @grb.setter
    def grb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ptp(self)->dvec3: ...

    @property
    def ppts(self)->dvec4: ...

    @property
    def bggb(self)->dvec4: ...

    @property
    def rrb(self)->dvec3: ...

    @property
    def rbrb(self)->dvec4: ...

    @property
    def sss(self)->dvec3: ...

    @property
    def sppt(self)->dvec4: ...

    @property
    def rrrr(self)->dvec4: ...

    @property
    def bbrg(self)->dvec4: ...

    @property
    def spp(self)->dvec3: ...

    @property
    def yzxy(self)->dvec4: ...

    @property
    def gbbb(self)->dvec4: ...

    @property
    def bgrb(self)->dvec4: ...

    @property
    def brrr(self)->dvec4: ...

    @property
    def grgr(self)->dvec4: ...

    @property
    def yxyx(self)->dvec4: ...

    @property
    def zyzx(self)->dvec4: ...

    @property
    def yxxx(self)->dvec4: ...

    @property
    def spss(self)->dvec4: ...

    @property
    def ptss(self)->dvec4: ...

    @property
    def xyzx(self)->dvec4: ...

    @property
    def stps(self)->dvec4: ...

    @property
    def gbgg(self)->dvec4: ...

    @property
    def ttpt(self)->dvec4: ...

    @property
    def ggrr(self)->dvec4: ...

    @property
    def psst(self)->dvec4: ...

    @property
    def bgr(self)->dvec3: ...

    @bgr.setter
    def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def brgb(self)->dvec4: ...

    @property
    def yzzx(self)->dvec4: ...

    @property
    def stt(self)->dvec3: ...

    @property
    def ptpt(self)->dvec4: ...

    @property
    def ggbg(self)->dvec4: ...

    @property
    def tpst(self)->dvec4: ...

    @property
    def gr(self)->dvec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def sttt(self)->dvec4: ...

    @property
    def brrg(self)->dvec4: ...

    @property
    def sptp(self)->dvec4: ...

    @property
    def ppps(self)->dvec4: ...

    @property
    def xzzz(self)->dvec4: ...

    @property
    def ttss(self)->dvec4: ...

    @property
    def ssss(self)->dvec4: ...

    @property
    def yxxy(self)->dvec4: ...

    @property
    def tpsp(self)->dvec4: ...

    @property
    def pss(self)->dvec3: ...

    @property
    def bbrb(self)->dvec4: ...

    @property
    def zxzz(self)->dvec4: ...

    @property
    def yxxz(self)->dvec4: ...

    @property
    def zxz(self)->dvec3: ...

    @property
    def xxyz(self)->dvec4: ...

    @property
    def y(self)->float: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def yzxx(self)->dvec4: ...

    @property
    def zyxy(self)->dvec4: ...

    @property
    def ttp(self)->dvec3: ...

    @property
    def zzx(self)->dvec3: ...

    @property
    def bb(self)->dvec2: ...

    @property
    def xzyx(self)->dvec4: ...

    @property
    def ggrb(self)->dvec4: ...

    @property
    def zxzy(self)->dvec4: ...

    @property
    def gbb(self)->dvec3: ...

    @property
    def bbgg(self)->dvec4: ...

    @property
    def brgg(self)->dvec4: ...

    @property
    def grgb(self)->dvec4: ...

    @property
    def xxy(self)->dvec3: ...

    @property
    def xyxz(self)->dvec4: ...

    @property
    def ss(self)->dvec2: ...

    @property
    def xz(self)->dvec2: ...

    @xz.setter
    def xz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def stsp(self)->dvec4: ...

    @property
    def bg(self)->dvec2: ...

    @bg.setter
    def bg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tp(self)->dvec2: ...

    @tp.setter
    def tp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def pppt(self)->dvec4: ...

    @property
    def yzyy(self)->dvec4: ...

    @property
    def yzy(self)->dvec3: ...

    @property
    def yyy(self)->dvec3: ...

    @property
    def yyyy(self)->dvec4: ...

    @property
    def st(self)->dvec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yxyy(self)->dvec4: ...

    @property
    def yyz(self)->dvec3: ...

    @property
    def rrbb(self)->dvec4: ...

    @property
    def rbgr(self)->dvec4: ...

    @property
    def tppp(self)->dvec4: ...

    @property
    def rrbg(self)->dvec4: ...

    @property
    def sptt(self)->dvec4: ...

    @property
    def xzyz(self)->dvec4: ...

    @property
    def ppt(self)->dvec3: ...

    @property
    def xxzx(self)->dvec4: ...

    @property
    def spst(self)->dvec4: ...

    @property
    def rgbg(self)->dvec4: ...

    @property
    def brbr(self)->dvec4: ...

    @property
    def zzz(self)->dvec3: ...

    @property
    def ssts(self)->dvec4: ...

    @property
    def bgb(self)->dvec3: ...

    @property
    def ptps(self)->dvec4: ...

    @property
    def pspt(self)->dvec4: ...

    @property
    def pstt(self)->dvec4: ...

    @property
    def xzzy(self)->dvec4: ...

    @property
    def ttpp(self)->dvec4: ...

    @property
    def ggb(self)->dvec3: ...

    @property
    def yzx(self)->dvec3: ...

    @yzx.setter
    def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ssp(self)->dvec3: ...

    @property
    def rgrb(self)->dvec4: ...

    @property
    def grrr(self)->dvec4: ...

    @property
    def gbr(self)->dvec3: ...

    @gbr.setter
    def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def grr(self)->dvec3: ...

    @property
    def tpts(self)->dvec4: ...

    @property
    def pp(self)->dvec2: ...

    @property
    def yzxz(self)->dvec4: ...

    @property
    def xyyz(self)->dvec4: ...

    @property
    def yx(self)->dvec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def x(self)->float: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def yyx(self)->dvec3: ...

    @property
    def g(self)->float: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def spts(self)->dvec4: ...

    @property
    def gbrr(self)->dvec4: ...

    @property
    def grg(self)->dvec3: ...

    @property
    def xxyx(self)->dvec4: ...

    @property
    def rbgb(self)->dvec4: ...

    @property
    def yxzz(self)->dvec4: ...

    @property
    def ssps(self)->dvec4: ...

    @property
    def zzyx(self)->dvec4: ...

    @property
    def spsp(self)->dvec4: ...

    @property
    def zxy(self)->dvec3: ...

    @zxy.setter
    def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tptp(self)->dvec4: ...

    @property
    def ggr(self)->dvec3: ...

    @property
    def rggb(self)->dvec4: ...

    @property
    def sspt(self)->dvec4: ...

    @property
    def bgbb(self)->dvec4: ...

    @property
    def pspp(self)->dvec4: ...

    @property
    def ppsp(self)->dvec4: ...

    @property
    def rrgb(self)->dvec4: ...

    @property
    def zyy(self)->dvec3: ...

    @property
    def zzxx(self)->dvec4: ...

    @property
    def brr(self)->dvec3: ...

    @property
    def rrbr(self)->dvec4: ...

    @property
    def yy(self)->dvec2: ...

    @property
    def ts(self)->dvec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tps(self)->dvec3: ...

    @tps.setter
    def tps(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zxxy(self)->dvec4: ...

    @property
    def zzy(self)->dvec3: ...

    @property
    def tss(self)->dvec3: ...

    @property
    def yyxx(self)->dvec4: ...

    @property
    def zzzy(self)->dvec4: ...

    @property
    def psps(self)->dvec4: ...

    @property
    def bbgb(self)->dvec4: ...

    @property
    def gbbr(self)->dvec4: ...

    @property
    def yzzy(self)->dvec4: ...

    @property
    def sp(self)->dvec2: ...

    @sp.setter
    def sp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zyxx(self)->dvec4: ...

    @property
    def yzyz(self)->dvec4: ...

    @property
    def rgbr(self)->dvec4: ...

    @property
    def bggr(self)->dvec4: ...

    @property
    def xyyx(self)->dvec4: ...

    @property
    def xyxy(self)->dvec4: ...

    @property
    def r(self)->float: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def bgbr(self)->dvec4: ...

    @property
    def tspp(self)->dvec4: ...

    @property
    def tpss(self)->dvec4: ...

    @property
    def tpp(self)->dvec3: ...

    @property
    def zy(self)->dvec2: ...

    @zy.setter
    def zy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xzxx(self)->dvec4: ...

    @property
    def bbb(self)->dvec3: ...

    @property
    def gggr(self)->dvec4: ...

    @property
    def sttp(self)->dvec4: ...

    @property
    def tppt(self)->dvec4: ...

    @property
    def zyzy(self)->dvec4: ...

    @property
    def ttt(self)->dvec3: ...

    @property
    def tspt(self)->dvec4: ...

    @property
    def tstt(self)->dvec4: ...

    @property
    def sts(self)->dvec3: ...

    @property
    def ttts(self)->dvec4: ...

    @property
    def xxzy(self)->dvec4: ...

    @property
    def stp(self)->dvec3: ...

    @stp.setter
    def stp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ggrg(self)->dvec4: ...

    @property
    def tptt(self)->dvec4: ...

    @property
    def brbg(self)->dvec4: ...

    @property
    def xxyy(self)->dvec4: ...

    @property
    def pps(self)->dvec3: ...

    @property
    def rggg(self)->dvec4: ...

    @property
    def bgbg(self)->dvec4: ...

    @property
    def p(self)->float: ...

    @p.setter
    def p(self, value:Union[bool, int, float])->None: ...

    @property
    def sspp(self)->dvec4: ...

    @property
    def tts(self)->dvec3: ...

    @property
    def xyyy(self)->dvec4: ...

    @property
    def yyxy(self)->dvec4: ...

    @property
    def sps(self)->dvec3: ...

    @property
    def ptsp(self)->dvec4: ...

    @property
    def s(self)->float: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def zxzx(self)->dvec4: ...

    @property
    def zyyx(self)->dvec4: ...

    @property
    def xzzx(self)->dvec4: ...

    @property
    def sst(self)->dvec3: ...
