from typing import override, Union

from .genVec2 import genVec2
from .dvec3 import dvec3
from .dvec4 import dvec4


class dvec2(genVec2):

    @property
    def x(self)->float: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->float: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->dvec2: ...

    @property
    def xy(self)->dvec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->dvec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->dvec2: ...

    @property
    def xxx(self)->dvec3: ...

    @property
    def xxy(self)->dvec3: ...

    @property
    def xyx(self)->dvec3: ...

    @property
    def xyy(self)->dvec3: ...

    @property
    def yxx(self)->dvec3: ...

    @property
    def yxy(self)->dvec3: ...

    @property
    def yyx(self)->dvec3: ...

    @property
    def yyy(self)->dvec3: ...

    @property
    def xxxx(self)->dvec4: ...

    @property
    def xxxy(self)->dvec4: ...

    @property
    def xxyx(self)->dvec4: ...

    @property
    def xxyy(self)->dvec4: ...

    @property
    def xyxx(self)->dvec4: ...

    @property
    def xyxy(self)->dvec4: ...

    @property
    def xyyx(self)->dvec4: ...

    @property
    def xyyy(self)->dvec4: ...

    @property
    def yxxx(self)->dvec4: ...

    @property
    def yxxy(self)->dvec4: ...

    @property
    def yxyx(self)->dvec4: ...

    @property
    def yxyy(self)->dvec4: ...

    @property
    def yyxx(self)->dvec4: ...

    @property
    def yyxy(self)->dvec4: ...

    @property
    def yyyx(self)->dvec4: ...

    @property
    def yyyy(self)->dvec4: ...

    @property
    def r(self)->float: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->float: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->dvec2: ...

    @property
    def rg(self)->dvec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->dvec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->dvec2: ...

    @property
    def rrr(self)->dvec3: ...

    @property
    def rrg(self)->dvec3: ...

    @property
    def rgr(self)->dvec3: ...

    @property
    def rgg(self)->dvec3: ...

    @property
    def grr(self)->dvec3: ...

    @property
    def grg(self)->dvec3: ...

    @property
    def ggr(self)->dvec3: ...

    @property
    def ggg(self)->dvec3: ...

    @property
    def rrrr(self)->dvec4: ...

    @property
    def rrrg(self)->dvec4: ...

    @property
    def rrgr(self)->dvec4: ...

    @property
    def rrgg(self)->dvec4: ...

    @property
    def rgrr(self)->dvec4: ...

    @property
    def rgrg(self)->dvec4: ...

    @property
    def rggr(self)->dvec4: ...

    @property
    def rggg(self)->dvec4: ...

    @property
    def grrr(self)->dvec4: ...

    @property
    def grrg(self)->dvec4: ...

    @property
    def grgr(self)->dvec4: ...

    @property
    def grgg(self)->dvec4: ...

    @property
    def ggrr(self)->dvec4: ...

    @property
    def ggrg(self)->dvec4: ...

    @property
    def gggr(self)->dvec4: ...

    @property
    def gggg(self)->dvec4: ...

    @property
    def s(self)->float: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->float: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def ss(self)->dvec2: ...

    @property
    def st(self)->dvec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ts(self)->dvec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tt(self)->dvec2: ...

    @property
    def sss(self)->dvec3: ...

    @property
    def sst(self)->dvec3: ...

    @property
    def sts(self)->dvec3: ...

    @property
    def stt(self)->dvec3: ...

    @property
    def tss(self)->dvec3: ...

    @property
    def tst(self)->dvec3: ...

    @property
    def tts(self)->dvec3: ...

    @property
    def ttt(self)->dvec3: ...

    @property
    def ssss(self)->dvec4: ...

    @property
    def ssst(self)->dvec4: ...

    @property
    def ssts(self)->dvec4: ...

    @property
    def sstt(self)->dvec4: ...

    @property
    def stss(self)->dvec4: ...

    @property
    def stst(self)->dvec4: ...

    @property
    def stts(self)->dvec4: ...

    @property
    def sttt(self)->dvec4: ...

    @property
    def tsss(self)->dvec4: ...

    @property
    def tsst(self)->dvec4: ...

    @property
    def tsts(self)->dvec4: ...

    @property
    def tstt(self)->dvec4: ...

    @property
    def ttss(self)->dvec4: ...

    @property
    def ttst(self)->dvec4: ...

    @property
    def ttts(self)->dvec4: ...

    @property
    def tttt(self)->dvec4: ...
