
    @property
    def rrrr(self)->ivec4: ...

    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def grrg(self)->ivec4: ...

    @property
    def rgrr(self)->ivec4: ...

    @property
    def tt(self)->ivec2: ...

    @property
    def rrgr(self)->ivec4: ...

    @property
    def grgr(self)->ivec4: ...

    @property
    def yxyx(self)->ivec4: ...

    @property
    def yyx(self)->ivec3: ...

    @property
    def yxxx(self)->ivec4: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->int: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def grg(self)->ivec3: ...

    @property
    def xxyx(self)->ivec4: ...

    @property
    def ggg(self)->ivec3: ...

    @property
    def ggrr(self)->ivec4: ...

    @property
    def yyyx(self)->ivec4: ...

    @property
    def tsss(self)->ivec4: ...

    @property
    def tsst(self)->ivec4: ...

    @property
    def yxy(self)->ivec3: ...

    @property
    def ggr(self)->ivec3: ...

    @property
    def stt(self)->ivec3: ...

    @property
    def tttt(self)->ivec4: ...

    @property
    def gr(self)->ivec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->ivec2: ...

    @property
    def sttt(self)->ivec4: ...

    @property
    def ttss(self)->ivec4: ...

    @property
    def stst(self)->ivec4: ...

    @property
    def ssss(self)->ivec4: ...

    @property
    def rrgg(self)->ivec4: ...

    @property
    def yxxy(self)->ivec4: ...

    @property
    def yy(self)->ivec2: ...

    @property
    def ts(self)->ivec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rrr(self)->ivec3: ...

    @property
    def tss(self)->ivec3: ...

    @property
    def yyxx(self)->ivec4: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xxxx(self)->ivec4: ...

    @property
    def xyxx(self)->ivec4: ...

    @property
    def rgr(self)->ivec3: ...

    @property
    def xxy(self)->ivec3: ...

    @property
    def xyyx(self)->ivec4: ...

    @property
    def rrrg(self)->ivec4: ...

    @property
    def xyxy(self)->ivec4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def rgrg(self)->ivec4: ...

    @property
    def ss(self)->ivec2: ...

    @property
    def grgg(self)->ivec4: ...

    @property
    def xxxy(self)->ivec4: ...

    @property
    def yyy(self)->ivec3: ...

    @property
    def gggr(self)->ivec4: ...

    @property
    def yyyy(self)->ivec4: ...

    @property
    def st(self)->ivec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yxyy(self)->ivec4: ...

    @property
    def xyy(self)->ivec3: ...

    @property
    def ttt(self)->ivec3: ...

    @property
    def rrg(self)->ivec3: ...

    @property
    def tstt(self)->ivec4: ...

    @property
    def xx(self)->ivec2: ...

    @property
    def sts(self)->ivec3: ...

    @property
    def ttts(self)->ivec4: ...

    @property
    def ggrg(self)->ivec4: ...

    @property
    def stts(self)->ivec4: ...

    @property
    def ssts(self)->ivec4: ...

    @property
    def rgg(self)->ivec3: ...

    @property
    def xxyy(self)->ivec4: ...

    @property
    def gggg(self)->ivec4: ...

    @property
    def tst(self)->ivec3: ...

    @property
    def rg(self)->ivec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rggr(self)->ivec4: ...

    @property
    def rggg(self)->ivec4: ...

    @property
    def stss(self)->ivec4: ...

    @property
    def xxx(self)->ivec3: ...

    @property
    def sstt(self)->ivec4: ...

    @property
    def xy(self)->ivec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rr(self)->ivec2: ...

    @property
    def ttst(self)->ivec4: ...

    @property
    def yxx(self)->ivec3: ...

    @property
    def grrr(self)->ivec4: ...

    @property
    def tts(self)->ivec3: ...

    @property
    def xyyy(self)->ivec4: ...

    @property
    def xyx(self)->ivec3: ...

    @property
    def ssst(self)->ivec4: ...

    @property
    def tsts(self)->ivec4: ...

    @property
    def grr(self)->ivec3: ...

    @property
    def yyxy(self)->ivec4: ...

    @property
    def yx(self)->ivec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s(self)->int: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def sss(self)->ivec3: ...

    @property
    def sst(self)->ivec3: ...
