from typing import override, Union

from .genVec2 import genVec2
from .genVec3 import genVec3
from .genVec4 import genVec4
from .uvec2 import uvec2
from .uvec3 import uvec3


class uvec4(genVec4):
    
    def __init__(self): ...

    @override
    def __init__(self, x:Union[bool,int,float]): ...

    @override
    def __init__(self, vec:genVec4): ...

    @override
    def __init__(self, x:Union[bool,int,float], vec:genVec3): ...

    @override
    def __init__(self, vec:genVec3, z:Union[bool,int,float]): ...

    @override
    def __init__(self, vec_1:genVec2, vec_2:genVec2): ...

    @override
    def __init__(self, x:Union[bool,int,float], y:Union[bool,int,float], vec:genVec2): ...

    @override
    def __init__(self, vec:genVec2, z:Union[bool,int,float], w:Union[bool,int,float]): ...

    @override
    def __init__(self, x:Union[bool,int,float], vec:genVec2, z:Union[bool,int,float]): ...

    @override
    def __init__(self, x:Union[bool,int,float], y:Union[bool,int,float], z:Union[bool,int,float], w:Union[bool,int,float]): ...

    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def z(self)->int: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def w(self)->int: ...

    @w.setter
    def w(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->uvec2: ...

    @property
    def xy(self)->uvec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xz(self)->uvec2: ...

    @xz.setter
    def xz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xw(self)->uvec2: ...

    @xw.setter
    def xw(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->uvec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->uvec2: ...

    @property
    def yz(self)->uvec2: ...

    @yz.setter
    def yz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yw(self)->uvec2: ...

    @yw.setter
    def yw(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zx(self)->uvec2: ...

    @zx.setter
    def zx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zy(self)->uvec2: ...

    @zy.setter
    def zy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zz(self)->uvec2: ...

    @property
    def zw(self)->uvec2: ...

    @zw.setter
    def zw(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def wx(self)->uvec2: ...

    @wx.setter
    def wx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def wy(self)->uvec2: ...

    @wy.setter
    def wy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def wz(self)->uvec2: ...

    @wz.setter
    def wz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ww(self)->uvec2: ...

    @property
    def xxx(self)->uvec3: ...

    @property
    def xxy(self)->uvec3: ...

    @property
    def xxz(self)->uvec3: ...

    @property
    def xxw(self)->uvec3: ...

    @property
    def xyx(self)->uvec3: ...

    @property
    def xyy(self)->uvec3: ...

    @property
    def xyz(self)->uvec3: ...

    @xyz.setter
    def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xyw(self)->uvec3: ...

    @xyw.setter
    def xyw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzx(self)->uvec3: ...

    @property
    def xzy(self)->uvec3: ...

    @xzy.setter
    def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzz(self)->uvec3: ...

    @property
    def xzw(self)->uvec3: ...

    @xzw.setter
    def xzw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xwx(self)->uvec3: ...

    @property
    def xwy(self)->uvec3: ...

    @xwy.setter
    def xwy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xwz(self)->uvec3: ...

    @xwz.setter
    def xwz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xww(self)->uvec3: ...

    @property
    def yxx(self)->uvec3: ...

    @property
    def yxy(self)->uvec3: ...

    @property
    def yxz(self)->uvec3: ...

    @yxz.setter
    def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yxw(self)->uvec3: ...

    @yxw.setter
    def yxw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yyx(self)->uvec3: ...

    @property
    def yyy(self)->uvec3: ...

    @property
    def yyz(self)->uvec3: ...

    @property
    def yyw(self)->uvec3: ...

    @property
    def yzx(self)->uvec3: ...

    @yzx.setter
    def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yzy(self)->uvec3: ...

    @property
    def yzz(self)->uvec3: ...

    @property
    def yzw(self)->uvec3: ...

    @yzw.setter
    def yzw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ywx(self)->uvec3: ...

    @ywx.setter
    def ywx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ywy(self)->uvec3: ...

    @property
    def ywz(self)->uvec3: ...

    @ywz.setter
    def ywz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yww(self)->uvec3: ...

    @property
    def zxx(self)->uvec3: ...

    @property
    def zxy(self)->uvec3: ...

    @zxy.setter
    def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zxz(self)->uvec3: ...

    @property
    def zxw(self)->uvec3: ...

    @zxw.setter
    def zxw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyx(self)->uvec3: ...

    @zyx.setter
    def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyy(self)->uvec3: ...

    @property
    def zyz(self)->uvec3: ...

    @property
    def zyw(self)->uvec3: ...

    @zyw.setter
    def zyw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zzx(self)->uvec3: ...

    @property
    def zzy(self)->uvec3: ...

    @property
    def zzz(self)->uvec3: ...

    @property
    def zzw(self)->uvec3: ...

    @property
    def zwx(self)->uvec3: ...

    @zwx.setter
    def zwx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zwy(self)->uvec3: ...

    @zwy.setter
    def zwy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zwz(self)->uvec3: ...

    @property
    def zww(self)->uvec3: ...

    @property
    def wxx(self)->uvec3: ...

    @property
    def wxy(self)->uvec3: ...

    @wxy.setter
    def wxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wxz(self)->uvec3: ...

    @wxz.setter
    def wxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wxw(self)->uvec3: ...

    @property
    def wyx(self)->uvec3: ...

    @wyx.setter
    def wyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wyy(self)->uvec3: ...

    @property
    def wyz(self)->uvec3: ...

    @wyz.setter
    def wyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wyw(self)->uvec3: ...

    @property
    def wzx(self)->uvec3: ...

    @wzx.setter
    def wzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wzy(self)->uvec3: ...

    @wzy.setter
    def wzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wzz(self)->uvec3: ...

    @property
    def wzw(self)->uvec3: ...

    @property
    def wwx(self)->uvec3: ...

    @property
    def wwy(self)->uvec3: ...

    @property
    def wwz(self)->uvec3: ...

    @property
    def www(self)->uvec3: ...

    @property
    def xxxx(self)->uvec4: ...

    @property
    def xxxy(self)->uvec4: ...

    @property
    def xxxz(self)->uvec4: ...

    @property
    def xxxw(self)->uvec4: ...

    @property
    def xxyx(self)->uvec4: ...

    @property
    def xxyy(self)->uvec4: ...

    @property
    def xxyz(self)->uvec4: ...

    @property
    def xxyw(self)->uvec4: ...

    @property
    def xxzx(self)->uvec4: ...

    @property
    def xxzy(self)->uvec4: ...

    @property
    def xxzz(self)->uvec4: ...

    @property
    def xxzw(self)->uvec4: ...

    @property
    def xxwx(self)->uvec4: ...

    @property
    def xxwy(self)->uvec4: ...

    @property
    def xxwz(self)->uvec4: ...

    @property
    def xxww(self)->uvec4: ...

    @property
    def xyxx(self)->uvec4: ...

    @property
    def xyxy(self)->uvec4: ...

    @property
    def xyxz(self)->uvec4: ...

    @property
    def xyxw(self)->uvec4: ...

    @property
    def xyyx(self)->uvec4: ...

    @property
    def xyyy(self)->uvec4: ...

    @property
    def xyyz(self)->uvec4: ...

    @property
    def xyyw(self)->uvec4: ...

    @property
    def xyzx(self)->uvec4: ...

    @property
    def xyzy(self)->uvec4: ...

    @property
    def xyzz(self)->uvec4: ...

    @property
    def xyzw(self)->uvec4: ...

    @xyzw.setter
    def xyzw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xywx(self)->uvec4: ...

    @property
    def xywy(self)->uvec4: ...

    @property
    def xywz(self)->uvec4: ...

    @xywz.setter
    def xywz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xyww(self)->uvec4: ...

    @property
    def xzxx(self)->uvec4: ...

    @property
    def xzxy(self)->uvec4: ...

    @property
    def xzxz(self)->uvec4: ...

    @property
    def xzxw(self)->uvec4: ...

    @property
    def xzyx(self)->uvec4: ...

    @property
    def xzyy(self)->uvec4: ...

    @property
    def xzyz(self)->uvec4: ...

    @property
    def xzyw(self)->uvec4: ...

    @xzyw.setter
    def xzyw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xzzx(self)->uvec4: ...

    @property
    def xzzy(self)->uvec4: ...

    @property
    def xzzz(self)->uvec4: ...

    @property
    def xzzw(self)->uvec4: ...

    @property
    def xzwx(self)->uvec4: ...

    @property
    def xzwy(self)->uvec4: ...

    @xzwy.setter
    def xzwy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xzwz(self)->uvec4: ...

    @property
    def xzww(self)->uvec4: ...

    @property
    def xwxx(self)->uvec4: ...

    @property
    def xwxy(self)->uvec4: ...

    @property
    def xwxz(self)->uvec4: ...

    @property
    def xwxw(self)->uvec4: ...

    @property
    def xwyx(self)->uvec4: ...

    @property
    def xwyy(self)->uvec4: ...

    @property
    def xwyz(self)->uvec4: ...

    @xwyz.setter
    def xwyz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xwyw(self)->uvec4: ...

    @property
    def xwzx(self)->uvec4: ...

    @property
    def xwzy(self)->uvec4: ...

    @xwzy.setter
    def xwzy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xwzz(self)->uvec4: ...

    @property
    def xwzw(self)->uvec4: ...

    @property
    def xwwx(self)->uvec4: ...

    @property
    def xwwy(self)->uvec4: ...

    @property
    def xwwz(self)->uvec4: ...

    @property
    def xwww(self)->uvec4: ...

    @property
    def yxxx(self)->uvec4: ...

    @property
    def yxxy(self)->uvec4: ...

    @property
    def yxxz(self)->uvec4: ...

    @property
    def yxxw(self)->uvec4: ...

    @property
    def yxyx(self)->uvec4: ...

    @property
    def yxyy(self)->uvec4: ...

    @property
    def yxyz(self)->uvec4: ...

    @property
    def yxyw(self)->uvec4: ...

    @property
    def yxzx(self)->uvec4: ...

    @property
    def yxzy(self)->uvec4: ...

    @property
    def yxzz(self)->uvec4: ...

    @property
    def yxzw(self)->uvec4: ...

    @yxzw.setter
    def yxzw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yxwx(self)->uvec4: ...

    @property
    def yxwy(self)->uvec4: ...

    @property
    def yxwz(self)->uvec4: ...

    @yxwz.setter
    def yxwz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yxww(self)->uvec4: ...

    @property
    def yyxx(self)->uvec4: ...

    @property
    def yyxy(self)->uvec4: ...

    @property
    def yyxz(self)->uvec4: ...

    @property
    def yyxw(self)->uvec4: ...

    @property
    def yyyx(self)->uvec4: ...

    @property
    def yyyy(self)->uvec4: ...

    @property
    def yyyz(self)->uvec4: ...

    @property
    def yyyw(self)->uvec4: ...

    @property
    def yyzx(self)->uvec4: ...

    @property
    def yyzy(self)->uvec4: ...

    @property
    def yyzz(self)->uvec4: ...

    @property
    def yyzw(self)->uvec4: ...

    @property
    def yywx(self)->uvec4: ...

    @property
    def yywy(self)->uvec4: ...

    @property
    def yywz(self)->uvec4: ...

    @property
    def yyww(self)->uvec4: ...

    @property
    def yzxx(self)->uvec4: ...

    @property
    def yzxy(self)->uvec4: ...

    @property
    def yzxz(self)->uvec4: ...

    @property
    def yzxw(self)->uvec4: ...

    @yzxw.setter
    def yzxw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yzyx(self)->uvec4: ...

    @property
    def yzyy(self)->uvec4: ...

    @property
    def yzyz(self)->uvec4: ...

    @property
    def yzyw(self)->uvec4: ...

    @property
    def yzzx(self)->uvec4: ...

    @property
    def yzzy(self)->uvec4: ...

    @property
    def yzzz(self)->uvec4: ...

    @property
    def yzzw(self)->uvec4: ...

    @property
    def yzwx(self)->uvec4: ...

    @yzwx.setter
    def yzwx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yzwy(self)->uvec4: ...

    @property
    def yzwz(self)->uvec4: ...

    @property
    def yzww(self)->uvec4: ...

    @property
    def ywxx(self)->uvec4: ...

    @property
    def ywxy(self)->uvec4: ...

    @property
    def ywxz(self)->uvec4: ...

    @ywxz.setter
    def ywxz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def ywxw(self)->uvec4: ...

    @property
    def ywyx(self)->uvec4: ...

    @property
    def ywyy(self)->uvec4: ...

    @property
    def ywyz(self)->uvec4: ...

    @property
    def ywyw(self)->uvec4: ...

    @property
    def ywzx(self)->uvec4: ...

    @ywzx.setter
    def ywzx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def ywzy(self)->uvec4: ...

    @property
    def ywzz(self)->uvec4: ...

    @property
    def ywzw(self)->uvec4: ...

    @property
    def ywwx(self)->uvec4: ...

    @property
    def ywwy(self)->uvec4: ...

    @property
    def ywwz(self)->uvec4: ...

    @property
    def ywww(self)->uvec4: ...

    @property
    def zxxx(self)->uvec4: ...

    @property
    def zxxy(self)->uvec4: ...

    @property
    def zxxz(self)->uvec4: ...

    @property
    def zxxw(self)->uvec4: ...

    @property
    def zxyx(self)->uvec4: ...

    @property
    def zxyy(self)->uvec4: ...

    @property
    def zxyz(self)->uvec4: ...

    @property
    def zxyw(self)->uvec4: ...

    @zxyw.setter
    def zxyw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zxzx(self)->uvec4: ...

    @property
    def zxzy(self)->uvec4: ...

    @property
    def zxzz(self)->uvec4: ...

    @property
    def zxzw(self)->uvec4: ...

    @property
    def zxwx(self)->uvec4: ...

    @property
    def zxwy(self)->uvec4: ...

    @zxwy.setter
    def zxwy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zxwz(self)->uvec4: ...

    @property
    def zxww(self)->uvec4: ...

    @property
    def zyxx(self)->uvec4: ...

    @property
    def zyxy(self)->uvec4: ...

    @property
    def zyxz(self)->uvec4: ...

    @property
    def zyxw(self)->uvec4: ...

    @zyxw.setter
    def zyxw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zyyx(self)->uvec4: ...

    @property
    def zyyy(self)->uvec4: ...

    @property
    def zyyz(self)->uvec4: ...

    @property
    def zyyw(self)->uvec4: ...

    @property
    def zyzx(self)->uvec4: ...

    @property
    def zyzy(self)->uvec4: ...

    @property
    def zyzz(self)->uvec4: ...

    @property
    def zyzw(self)->uvec4: ...

    @property
    def zywx(self)->uvec4: ...

    @zywx.setter
    def zywx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zywy(self)->uvec4: ...

    @property
    def zywz(self)->uvec4: ...

    @property
    def zyww(self)->uvec4: ...

    @property
    def zzxx(self)->uvec4: ...

    @property
    def zzxy(self)->uvec4: ...

    @property
    def zzxz(self)->uvec4: ...

    @property
    def zzxw(self)->uvec4: ...

    @property
    def zzyx(self)->uvec4: ...

    @property
    def zzyy(self)->uvec4: ...

    @property
    def zzyz(self)->uvec4: ...

    @property
    def zzyw(self)->uvec4: ...

    @property
    def zzzx(self)->uvec4: ...

    @property
    def zzzy(self)->uvec4: ...

    @property
    def zzzz(self)->uvec4: ...

    @property
    def zzzw(self)->uvec4: ...

    @property
    def zzwx(self)->uvec4: ...

    @property
    def zzwy(self)->uvec4: ...

    @property
    def zzwz(self)->uvec4: ...

    @property
    def zzww(self)->uvec4: ...

    @property
    def zwxx(self)->uvec4: ...

    @property
    def zwxy(self)->uvec4: ...

    @zwxy.setter
    def zwxy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zwxz(self)->uvec4: ...

    @property
    def zwxw(self)->uvec4: ...

    @property
    def zwyx(self)->uvec4: ...

    @zwyx.setter
    def zwyx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zwyy(self)->uvec4: ...

    @property
    def zwyz(self)->uvec4: ...

    @property
    def zwyw(self)->uvec4: ...

    @property
    def zwzx(self)->uvec4: ...

    @property
    def zwzy(self)->uvec4: ...

    @property
    def zwzz(self)->uvec4: ...

    @property
    def zwzw(self)->uvec4: ...

    @property
    def zwwx(self)->uvec4: ...

    @property
    def zwwy(self)->uvec4: ...

    @property
    def zwwz(self)->uvec4: ...

    @property
    def zwww(self)->uvec4: ...

    @property
    def wxxx(self)->uvec4: ...

    @property
    def wxxy(self)->uvec4: ...

    @property
    def wxxz(self)->uvec4: ...

    @property
    def wxxw(self)->uvec4: ...

    @property
    def wxyx(self)->uvec4: ...

    @property
    def wxyy(self)->uvec4: ...

    @property
    def wxyz(self)->uvec4: ...

    @wxyz.setter
    def wxyz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wxyw(self)->uvec4: ...

    @property
    def wxzx(self)->uvec4: ...

    @property
    def wxzy(self)->uvec4: ...

    @wxzy.setter
    def wxzy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wxzz(self)->uvec4: ...

    @property
    def wxzw(self)->uvec4: ...

    @property
    def wxwx(self)->uvec4: ...

    @property
    def wxwy(self)->uvec4: ...

    @property
    def wxwz(self)->uvec4: ...

    @property
    def wxww(self)->uvec4: ...

    @property
    def wyxx(self)->uvec4: ...

    @property
    def wyxy(self)->uvec4: ...

    @property
    def wyxz(self)->uvec4: ...

    @wyxz.setter
    def wyxz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wyxw(self)->uvec4: ...

    @property
    def wyyx(self)->uvec4: ...

    @property
    def wyyy(self)->uvec4: ...

    @property
    def wyyz(self)->uvec4: ...

    @property
    def wyyw(self)->uvec4: ...

    @property
    def wyzx(self)->uvec4: ...

    @wyzx.setter
    def wyzx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wyzy(self)->uvec4: ...

    @property
    def wyzz(self)->uvec4: ...

    @property
    def wyzw(self)->uvec4: ...

    @property
    def wywx(self)->uvec4: ...

    @property
    def wywy(self)->uvec4: ...

    @property
    def wywz(self)->uvec4: ...

    @property
    def wyww(self)->uvec4: ...

    @property
    def wzxx(self)->uvec4: ...

    @property
    def wzxy(self)->uvec4: ...

    @wzxy.setter
    def wzxy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wzxz(self)->uvec4: ...

    @property
    def wzxw(self)->uvec4: ...

    @property
    def wzyx(self)->uvec4: ...

    @wzyx.setter
    def wzyx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wzyy(self)->uvec4: ...

    @property
    def wzyz(self)->uvec4: ...

    @property
    def wzyw(self)->uvec4: ...

    @property
    def wzzx(self)->uvec4: ...

    @property
    def wzzy(self)->uvec4: ...

    @property
    def wzzz(self)->uvec4: ...

    @property
    def wzzw(self)->uvec4: ...

    @property
    def wzwx(self)->uvec4: ...

    @property
    def wzwy(self)->uvec4: ...

    @property
    def wzwz(self)->uvec4: ...

    @property
    def wzww(self)->uvec4: ...

    @property
    def wwxx(self)->uvec4: ...

    @property
    def wwxy(self)->uvec4: ...

    @property
    def wwxz(self)->uvec4: ...

    @property
    def wwxw(self)->uvec4: ...

    @property
    def wwyx(self)->uvec4: ...

    @property
    def wwyy(self)->uvec4: ...

    @property
    def wwyz(self)->uvec4: ...

    @property
    def wwyw(self)->uvec4: ...

    @property
    def wwzx(self)->uvec4: ...

    @property
    def wwzy(self)->uvec4: ...

    @property
    def wwzz(self)->uvec4: ...

    @property
    def wwzw(self)->uvec4: ...

    @property
    def wwwx(self)->uvec4: ...

    @property
    def wwwy(self)->uvec4: ...

    @property
    def wwwz(self)->uvec4: ...

    @property
    def wwww(self)->uvec4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def b(self)->int: ...

    @b.setter
    def b(self, value:Union[bool, int, float])->None: ...

    @property
    def a(self)->int: ...

    @a.setter
    def a(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->uvec2: ...

    @property
    def rg(self)->uvec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rb(self)->uvec2: ...

    @rb.setter
    def rb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ra(self)->uvec2: ...

    @ra.setter
    def ra(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->uvec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->uvec2: ...

    @property
    def gb(self)->uvec2: ...

    @gb.setter
    def gb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ga(self)->uvec2: ...

    @ga.setter
    def ga(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def br(self)->uvec2: ...

    @br.setter
    def br(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bg(self)->uvec2: ...

    @bg.setter
    def bg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bb(self)->uvec2: ...

    @property
    def ba(self)->uvec2: ...

    @ba.setter
    def ba(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ar(self)->uvec2: ...

    @ar.setter
    def ar(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ag(self)->uvec2: ...

    @ag.setter
    def ag(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ab(self)->uvec2: ...

    @ab.setter
    def ab(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def aa(self)->uvec2: ...

    @property
    def rrr(self)->uvec3: ...

    @property
    def rrg(self)->uvec3: ...

    @property
    def rrb(self)->uvec3: ...

    @property
    def rra(self)->uvec3: ...

    @property
    def rgr(self)->uvec3: ...

    @property
    def rgg(self)->uvec3: ...

    @property
    def rgb(self)->uvec3: ...

    @rgb.setter
    def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rga(self)->uvec3: ...

    @rga.setter
    def rga(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbr(self)->uvec3: ...

    @property
    def rbg(self)->uvec3: ...

    @rbg.setter
    def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbb(self)->uvec3: ...

    @property
    def rba(self)->uvec3: ...

    @rba.setter
    def rba(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rar(self)->uvec3: ...

    @property
    def rag(self)->uvec3: ...

    @rag.setter
    def rag(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rab(self)->uvec3: ...

    @rab.setter
    def rab(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def raa(self)->uvec3: ...

    @property
    def grr(self)->uvec3: ...

    @property
    def grg(self)->uvec3: ...

    @property
    def grb(self)->uvec3: ...

    @grb.setter
    def grb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gra(self)->uvec3: ...

    @gra.setter
    def gra(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ggr(self)->uvec3: ...

    @property
    def ggg(self)->uvec3: ...

    @property
    def ggb(self)->uvec3: ...

    @property
    def gga(self)->uvec3: ...

    @property
    def gbr(self)->uvec3: ...

    @gbr.setter
    def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gbg(self)->uvec3: ...

    @property
    def gbb(self)->uvec3: ...

    @property
    def gba(self)->uvec3: ...

    @gba.setter
    def gba(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gar(self)->uvec3: ...

    @gar.setter
    def gar(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gag(self)->uvec3: ...

    @property
    def gab(self)->uvec3: ...

    @gab.setter
    def gab(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gaa(self)->uvec3: ...

    @property
    def brr(self)->uvec3: ...

    @property
    def brg(self)->uvec3: ...

    @brg.setter
    def brg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def brb(self)->uvec3: ...

    @property
    def bra(self)->uvec3: ...

    @bra.setter
    def bra(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgr(self)->uvec3: ...

    @bgr.setter
    def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgg(self)->uvec3: ...

    @property
    def bgb(self)->uvec3: ...

    @property
    def bga(self)->uvec3: ...

    @bga.setter
    def bga(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bbr(self)->uvec3: ...

    @property
    def bbg(self)->uvec3: ...

    @property
    def bbb(self)->uvec3: ...

    @property
    def bba(self)->uvec3: ...

    @property
    def bar(self)->uvec3: ...

    @bar.setter
    def bar(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bag(self)->uvec3: ...

    @bag.setter
    def bag(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bab(self)->uvec3: ...

    @property
    def baa(self)->uvec3: ...

    @property
    def arr(self)->uvec3: ...

    @property
    def arg(self)->uvec3: ...

    @arg.setter
    def arg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def arb(self)->uvec3: ...

    @arb.setter
    def arb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ara(self)->uvec3: ...

    @property
    def agr(self)->uvec3: ...

    @agr.setter
    def agr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def agg(self)->uvec3: ...

    @property
    def agb(self)->uvec3: ...

    @agb.setter
    def agb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def aga(self)->uvec3: ...

    @property
    def abr(self)->uvec3: ...

    @abr.setter
    def abr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def abg(self)->uvec3: ...

    @abg.setter
    def abg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def abb(self)->uvec3: ...

    @property
    def aba(self)->uvec3: ...

    @property
    def aar(self)->uvec3: ...

    @property
    def aag(self)->uvec3: ...

    @property
    def aab(self)->uvec3: ...

    @property
    def aaa(self)->uvec3: ...

    @property
    def rrrr(self)->uvec4: ...

    @property
    def rrrg(self)->uvec4: ...

    @property
    def rrrb(self)->uvec4: ...

    @property
    def rrra(self)->uvec4: ...

    @property
    def rrgr(self)->uvec4: ...

    @property
    def rrgg(self)->uvec4: ...

    @property
    def rrgb(self)->uvec4: ...

    @property
    def rrga(self)->uvec4: ...

    @property
    def rrbr(self)->uvec4: ...

    @property
    def rrbg(self)->uvec4: ...

    @property
    def rrbb(self)->uvec4: ...

    @property
    def rrba(self)->uvec4: ...

    @property
    def rrar(self)->uvec4: ...

    @property
    def rrag(self)->uvec4: ...

    @property
    def rrab(self)->uvec4: ...

    @property
    def rraa(self)->uvec4: ...

    @property
    def rgrr(self)->uvec4: ...

    @property
    def rgrg(self)->uvec4: ...

    @property
    def rgrb(self)->uvec4: ...

    @property
    def rgra(self)->uvec4: ...

    @property
    def rggr(self)->uvec4: ...

    @property
    def rggg(self)->uvec4: ...

    @property
    def rggb(self)->uvec4: ...

    @property
    def rgga(self)->uvec4: ...

    @property
    def rgbr(self)->uvec4: ...

    @property
    def rgbg(self)->uvec4: ...

    @property
    def rgbb(self)->uvec4: ...

    @property
    def rgba(self)->uvec4: ...

    @rgba.setter
    def rgba(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rgar(self)->uvec4: ...

    @property
    def rgag(self)->uvec4: ...

    @property
    def rgab(self)->uvec4: ...

    @rgab.setter
    def rgab(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rgaa(self)->uvec4: ...

    @property
    def rbrr(self)->uvec4: ...

    @property
    def rbrg(self)->uvec4: ...

    @property
    def rbrb(self)->uvec4: ...

    @property
    def rbra(self)->uvec4: ...

    @property
    def rbgr(self)->uvec4: ...

    @property
    def rbgg(self)->uvec4: ...

    @property
    def rbgb(self)->uvec4: ...

    @property
    def rbga(self)->uvec4: ...

    @rbga.setter
    def rbga(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rbbr(self)->uvec4: ...

    @property
    def rbbg(self)->uvec4: ...

    @property
    def rbbb(self)->uvec4: ...

    @property
    def rbba(self)->uvec4: ...

    @property
    def rbar(self)->uvec4: ...

    @property
    def rbag(self)->uvec4: ...

    @rbag.setter
    def rbag(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rbab(self)->uvec4: ...

    @property
    def rbaa(self)->uvec4: ...

    @property
    def rarr(self)->uvec4: ...

    @property
    def rarg(self)->uvec4: ...

    @property
    def rarb(self)->uvec4: ...

    @property
    def rara(self)->uvec4: ...

    @property
    def ragr(self)->uvec4: ...

    @property
    def ragg(self)->uvec4: ...

    @property
    def ragb(self)->uvec4: ...

    @ragb.setter
    def ragb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def raga(self)->uvec4: ...

    @property
    def rabr(self)->uvec4: ...

    @property
    def rabg(self)->uvec4: ...

    @rabg.setter
    def rabg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rabb(self)->uvec4: ...

    @property
    def raba(self)->uvec4: ...

    @property
    def raar(self)->uvec4: ...

    @property
    def raag(self)->uvec4: ...

    @property
    def raab(self)->uvec4: ...

    @property
    def raaa(self)->uvec4: ...

    @property
    def grrr(self)->uvec4: ...

    @property
    def grrg(self)->uvec4: ...

    @property
    def grrb(self)->uvec4: ...

    @property
    def grra(self)->uvec4: ...

    @property
    def grgr(self)->uvec4: ...

    @property
    def grgg(self)->uvec4: ...

    @property
    def grgb(self)->uvec4: ...

    @property
    def grga(self)->uvec4: ...

    @property
    def grbr(self)->uvec4: ...

    @property
    def grbg(self)->uvec4: ...

    @property
    def grbb(self)->uvec4: ...

    @property
    def grba(self)->uvec4: ...

    @grba.setter
    def grba(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def grar(self)->uvec4: ...

    @property
    def grag(self)->uvec4: ...

    @property
    def grab(self)->uvec4: ...

    @grab.setter
    def grab(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def graa(self)->uvec4: ...

    @property
    def ggrr(self)->uvec4: ...

    @property
    def ggrg(self)->uvec4: ...

    @property
    def ggrb(self)->uvec4: ...

    @property
    def ggra(self)->uvec4: ...

    @property
    def gggr(self)->uvec4: ...

    @property
    def gggg(self)->uvec4: ...

    @property
    def gggb(self)->uvec4: ...

    @property
    def ggga(self)->uvec4: ...

    @property
    def ggbr(self)->uvec4: ...

    @property
    def ggbg(self)->uvec4: ...

    @property
    def ggbb(self)->uvec4: ...

    @property
    def ggba(self)->uvec4: ...

    @property
    def ggar(self)->uvec4: ...

    @property
    def ggag(self)->uvec4: ...

    @property
    def ggab(self)->uvec4: ...

    @property
    def ggaa(self)->uvec4: ...

    @property
    def gbrr(self)->uvec4: ...

    @property
    def gbrg(self)->uvec4: ...

    @property
    def gbrb(self)->uvec4: ...

    @property
    def gbra(self)->uvec4: ...

    @gbra.setter
    def gbra(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gbgr(self)->uvec4: ...

    @property
    def gbgg(self)->uvec4: ...

    @property
    def gbgb(self)->uvec4: ...

    @property
    def gbga(self)->uvec4: ...

    @property
    def gbbr(self)->uvec4: ...

    @property
    def gbbg(self)->uvec4: ...

    @property
    def gbbb(self)->uvec4: ...

    @property
    def gbba(self)->uvec4: ...

    @property
    def gbar(self)->uvec4: ...

    @gbar.setter
    def gbar(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gbag(self)->uvec4: ...

    @property
    def gbab(self)->uvec4: ...

    @property
    def gbaa(self)->uvec4: ...

    @property
    def garr(self)->uvec4: ...

    @property
    def garg(self)->uvec4: ...

    @property
    def garb(self)->uvec4: ...

    @garb.setter
    def garb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gara(self)->uvec4: ...

    @property
    def gagr(self)->uvec4: ...

    @property
    def gagg(self)->uvec4: ...

    @property
    def gagb(self)->uvec4: ...

    @property
    def gaga(self)->uvec4: ...

    @property
    def gabr(self)->uvec4: ...

    @gabr.setter
    def gabr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gabg(self)->uvec4: ...

    @property
    def gabb(self)->uvec4: ...

    @property
    def gaba(self)->uvec4: ...

    @property
    def gaar(self)->uvec4: ...

    @property
    def gaag(self)->uvec4: ...

    @property
    def gaab(self)->uvec4: ...

    @property
    def gaaa(self)->uvec4: ...

    @property
    def brrr(self)->uvec4: ...

    @property
    def brrg(self)->uvec4: ...

    @property
    def brrb(self)->uvec4: ...

    @property
    def brra(self)->uvec4: ...

    @property
    def brgr(self)->uvec4: ...

    @property
    def brgg(self)->uvec4: ...

    @property
    def brgb(self)->uvec4: ...

    @property
    def brga(self)->uvec4: ...

    @brga.setter
    def brga(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def brbr(self)->uvec4: ...

    @property
    def brbg(self)->uvec4: ...

    @property
    def brbb(self)->uvec4: ...

    @property
    def brba(self)->uvec4: ...

    @property
    def brar(self)->uvec4: ...

    @property
    def brag(self)->uvec4: ...

    @brag.setter
    def brag(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def brab(self)->uvec4: ...

    @property
    def braa(self)->uvec4: ...

    @property
    def bgrr(self)->uvec4: ...

    @property
    def bgrg(self)->uvec4: ...

    @property
    def bgrb(self)->uvec4: ...

    @property
    def bgra(self)->uvec4: ...

    @bgra.setter
    def bgra(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def bggr(self)->uvec4: ...

    @property
    def bggg(self)->uvec4: ...

    @property
    def bggb(self)->uvec4: ...

    @property
    def bgga(self)->uvec4: ...

    @property
    def bgbr(self)->uvec4: ...

    @property
    def bgbg(self)->uvec4: ...

    @property
    def bgbb(self)->uvec4: ...

    @property
    def bgba(self)->uvec4: ...

    @property
    def bgar(self)->uvec4: ...

    @bgar.setter
    def bgar(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def bgag(self)->uvec4: ...

    @property
    def bgab(self)->uvec4: ...

    @property
    def bgaa(self)->uvec4: ...

    @property
    def bbrr(self)->uvec4: ...

    @property
    def bbrg(self)->uvec4: ...

    @property
    def bbrb(self)->uvec4: ...

    @property
    def bbra(self)->uvec4: ...

    @property
    def bbgr(self)->uvec4: ...

    @property
    def bbgg(self)->uvec4: ...

    @property
    def bbgb(self)->uvec4: ...

    @property
    def bbga(self)->uvec4: ...

    @property
    def bbbr(self)->uvec4: ...

    @property
    def bbbg(self)->uvec4: ...

    @property
    def bbbb(self)->uvec4: ...

    @property
    def bbba(self)->uvec4: ...

    @property
    def bbar(self)->uvec4: ...

    @property
    def bbag(self)->uvec4: ...

    @property
    def bbab(self)->uvec4: ...

    @property
    def bbaa(self)->uvec4: ...

    @property
    def barr(self)->uvec4: ...

    @property
    def barg(self)->uvec4: ...

    @barg.setter
    def barg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def barb(self)->uvec4: ...

    @property
    def bara(self)->uvec4: ...

    @property
    def bagr(self)->uvec4: ...

    @bagr.setter
    def bagr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def bagg(self)->uvec4: ...

    @property
    def bagb(self)->uvec4: ...

    @property
    def baga(self)->uvec4: ...

    @property
    def babr(self)->uvec4: ...

    @property
    def babg(self)->uvec4: ...

    @property
    def babb(self)->uvec4: ...

    @property
    def baba(self)->uvec4: ...

    @property
    def baar(self)->uvec4: ...

    @property
    def baag(self)->uvec4: ...

    @property
    def baab(self)->uvec4: ...

    @property
    def baaa(self)->uvec4: ...

    @property
    def arrr(self)->uvec4: ...

    @property
    def arrg(self)->uvec4: ...

    @property
    def arrb(self)->uvec4: ...

    @property
    def arra(self)->uvec4: ...

    @property
    def argr(self)->uvec4: ...

    @property
    def argg(self)->uvec4: ...

    @property
    def argb(self)->uvec4: ...

    @argb.setter
    def argb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def arga(self)->uvec4: ...

    @property
    def arbr(self)->uvec4: ...

    @property
    def arbg(self)->uvec4: ...

    @arbg.setter
    def arbg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def arbb(self)->uvec4: ...

    @property
    def arba(self)->uvec4: ...

    @property
    def arar(self)->uvec4: ...

    @property
    def arag(self)->uvec4: ...

    @property
    def arab(self)->uvec4: ...

    @property
    def araa(self)->uvec4: ...

    @property
    def agrr(self)->uvec4: ...

    @property
    def agrg(self)->uvec4: ...

    @property
    def agrb(self)->uvec4: ...

    @agrb.setter
    def agrb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def agra(self)->uvec4: ...

    @property
    def aggr(self)->uvec4: ...

    @property
    def aggg(self)->uvec4: ...

    @property
    def aggb(self)->uvec4: ...

    @property
    def agga(self)->uvec4: ...

    @property
    def agbr(self)->uvec4: ...

    @agbr.setter
    def agbr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def agbg(self)->uvec4: ...

    @property
    def agbb(self)->uvec4: ...

    @property
    def agba(self)->uvec4: ...

    @property
    def agar(self)->uvec4: ...

    @property
    def agag(self)->uvec4: ...

    @property
    def agab(self)->uvec4: ...

    @property
    def agaa(self)->uvec4: ...

    @property
    def abrr(self)->uvec4: ...

    @property
    def abrg(self)->uvec4: ...

    @abrg.setter
    def abrg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def abrb(self)->uvec4: ...

    @property
    def abra(self)->uvec4: ...

    @property
    def abgr(self)->uvec4: ...

    @abgr.setter
    def abgr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def abgg(self)->uvec4: ...

    @property
    def abgb(self)->uvec4: ...

    @property
    def abga(self)->uvec4: ...

    @property
    def abbr(self)->uvec4: ...

    @property
    def abbg(self)->uvec4: ...

    @property
    def abbb(self)->uvec4: ...

    @property
    def abba(self)->uvec4: ...

    @property
    def abar(self)->uvec4: ...

    @property
    def abag(self)->uvec4: ...

    @property
    def abab(self)->uvec4: ...

    @property
    def abaa(self)->uvec4: ...

    @property
    def aarr(self)->uvec4: ...

    @property
    def aarg(self)->uvec4: ...

    @property
    def aarb(self)->uvec4: ...

    @property
    def aara(self)->uvec4: ...

    @property
    def aagr(self)->uvec4: ...

    @property
    def aagg(self)->uvec4: ...

    @property
    def aagb(self)->uvec4: ...

    @property
    def aaga(self)->uvec4: ...

    @property
    def aabr(self)->uvec4: ...

    @property
    def aabg(self)->uvec4: ...

    @property
    def aabb(self)->uvec4: ...

    @property
    def aaba(self)->uvec4: ...

    @property
    def aaar(self)->uvec4: ...

    @property
    def aaag(self)->uvec4: ...

    @property
    def aaab(self)->uvec4: ...

    @property
    def aaaa(self)->uvec4: ...

    @property
    def s(self)->int: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->int: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def p(self)->int: ...

    @p.setter
    def p(self, value:Union[bool, int, float])->None: ...

    @property
    def q(self)->int: ...

    @q.setter
    def q(self, value:Union[bool, int, float])->None: ...

    @property
    def ss(self)->uvec2: ...

    @property
    def st(self)->uvec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def sp(self)->uvec2: ...

    @sp.setter
    def sp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def sq(self)->uvec2: ...

    @sq.setter
    def sq(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ts(self)->uvec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tt(self)->uvec2: ...

    @property
    def tp(self)->uvec2: ...

    @tp.setter
    def tp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tq(self)->uvec2: ...

    @tq.setter
    def tq(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ps(self)->uvec2: ...

    @ps.setter
    def ps(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def pt(self)->uvec2: ...

    @pt.setter
    def pt(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def pp(self)->uvec2: ...

    @property
    def pq(self)->uvec2: ...

    @pq.setter
    def pq(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def qs(self)->uvec2: ...

    @qs.setter
    def qs(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def qt(self)->uvec2: ...

    @qt.setter
    def qt(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def qp(self)->uvec2: ...

    @qp.setter
    def qp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def qq(self)->uvec2: ...

    @property
    def sss(self)->uvec3: ...

    @property
    def sst(self)->uvec3: ...

    @property
    def ssp(self)->uvec3: ...

    @property
    def ssq(self)->uvec3: ...

    @property
    def sts(self)->uvec3: ...

    @property
    def stt(self)->uvec3: ...

    @property
    def stp(self)->uvec3: ...

    @stp.setter
    def stp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def stq(self)->uvec3: ...

    @stq.setter
    def stq(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def sps(self)->uvec3: ...

    @property
    def spt(self)->uvec3: ...

    @spt.setter
    def spt(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def spp(self)->uvec3: ...

    @property
    def spq(self)->uvec3: ...

    @spq.setter
    def spq(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def sqs(self)->uvec3: ...

    @property
    def sqt(self)->uvec3: ...

    @sqt.setter
    def sqt(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def sqp(self)->uvec3: ...

    @sqp.setter
    def sqp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def sqq(self)->uvec3: ...

    @property
    def tss(self)->uvec3: ...

    @property
    def tst(self)->uvec3: ...

    @property
    def tsp(self)->uvec3: ...

    @tsp.setter
    def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tsq(self)->uvec3: ...

    @tsq.setter
    def tsq(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tts(self)->uvec3: ...

    @property
    def ttt(self)->uvec3: ...

    @property
    def ttp(self)->uvec3: ...

    @property
    def ttq(self)->uvec3: ...

    @property
    def tps(self)->uvec3: ...

    @tps.setter
    def tps(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tpt(self)->uvec3: ...

    @property
    def tpp(self)->uvec3: ...

    @property
    def tpq(self)->uvec3: ...

    @tpq.setter
    def tpq(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tqs(self)->uvec3: ...

    @tqs.setter
    def tqs(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tqt(self)->uvec3: ...

    @property
    def tqp(self)->uvec3: ...

    @tqp.setter
    def tqp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tqq(self)->uvec3: ...

    @property
    def pss(self)->uvec3: ...

    @property
    def pst(self)->uvec3: ...

    @pst.setter
    def pst(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def psp(self)->uvec3: ...

    @property
    def psq(self)->uvec3: ...

    @psq.setter
    def psq(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def pts(self)->uvec3: ...

    @pts.setter
    def pts(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ptt(self)->uvec3: ...

    @property
    def ptp(self)->uvec3: ...

    @property
    def ptq(self)->uvec3: ...

    @ptq.setter
    def ptq(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def pps(self)->uvec3: ...

    @property
    def ppt(self)->uvec3: ...

    @property
    def ppp(self)->uvec3: ...

    @property
    def ppq(self)->uvec3: ...

    @property
    def pqs(self)->uvec3: ...

    @pqs.setter
    def pqs(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def pqt(self)->uvec3: ...

    @pqt.setter
    def pqt(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def pqp(self)->uvec3: ...

    @property
    def pqq(self)->uvec3: ...

    @property
    def qss(self)->uvec3: ...

    @property
    def qst(self)->uvec3: ...

    @qst.setter
    def qst(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def qsp(self)->uvec3: ...

    @qsp.setter
    def qsp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def qsq(self)->uvec3: ...

    @property
    def qts(self)->uvec3: ...

    @qts.setter
    def qts(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def qtt(self)->uvec3: ...

    @property
    def qtp(self)->uvec3: ...

    @qtp.setter
    def qtp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def qtq(self)->uvec3: ...

    @property
    def qps(self)->uvec3: ...

    @qps.setter
    def qps(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def qpt(self)->uvec3: ...

    @qpt.setter
    def qpt(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def qpp(self)->uvec3: ...

    @property
    def qpq(self)->uvec3: ...

    @property
    def qqs(self)->uvec3: ...

    @property
    def qqt(self)->uvec3: ...

    @property
    def qqp(self)->uvec3: ...

    @property
    def qqq(self)->uvec3: ...

    @property
    def ssss(self)->uvec4: ...

    @property
    def ssst(self)->uvec4: ...

    @property
    def sssp(self)->uvec4: ...

    @property
    def sssq(self)->uvec4: ...

    @property
    def ssts(self)->uvec4: ...

    @property
    def sstt(self)->uvec4: ...

    @property
    def sstp(self)->uvec4: ...

    @property
    def sstq(self)->uvec4: ...

    @property
    def ssps(self)->uvec4: ...

    @property
    def sspt(self)->uvec4: ...

    @property
    def sspp(self)->uvec4: ...

    @property
    def sspq(self)->uvec4: ...

    @property
    def ssqs(self)->uvec4: ...

    @property
    def ssqt(self)->uvec4: ...

    @property
    def ssqp(self)->uvec4: ...

    @property
    def ssqq(self)->uvec4: ...

    @property
    def stss(self)->uvec4: ...

    @property
    def stst(self)->uvec4: ...

    @property
    def stsp(self)->uvec4: ...

    @property
    def stsq(self)->uvec4: ...

    @property
    def stts(self)->uvec4: ...

    @property
    def sttt(self)->uvec4: ...

    @property
    def sttp(self)->uvec4: ...

    @property
    def sttq(self)->uvec4: ...

    @property
    def stps(self)->uvec4: ...

    @property
    def stpt(self)->uvec4: ...

    @property
    def stpp(self)->uvec4: ...

    @property
    def stpq(self)->uvec4: ...

    @stpq.setter
    def stpq(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def stqs(self)->uvec4: ...

    @property
    def stqt(self)->uvec4: ...

    @property
    def stqp(self)->uvec4: ...

    @stqp.setter
    def stqp(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def stqq(self)->uvec4: ...

    @property
    def spss(self)->uvec4: ...

    @property
    def spst(self)->uvec4: ...

    @property
    def spsp(self)->uvec4: ...

    @property
    def spsq(self)->uvec4: ...

    @property
    def spts(self)->uvec4: ...

    @property
    def sptt(self)->uvec4: ...

    @property
    def sptp(self)->uvec4: ...

    @property
    def sptq(self)->uvec4: ...

    @sptq.setter
    def sptq(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def spps(self)->uvec4: ...

    @property
    def sppt(self)->uvec4: ...

    @property
    def sppp(self)->uvec4: ...

    @property
    def sppq(self)->uvec4: ...

    @property
    def spqs(self)->uvec4: ...

    @property
    def spqt(self)->uvec4: ...

    @spqt.setter
    def spqt(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def spqp(self)->uvec4: ...

    @property
    def spqq(self)->uvec4: ...

    @property
    def sqss(self)->uvec4: ...

    @property
    def sqst(self)->uvec4: ...

    @property
    def sqsp(self)->uvec4: ...

    @property
    def sqsq(self)->uvec4: ...

    @property
    def sqts(self)->uvec4: ...

    @property
    def sqtt(self)->uvec4: ...

    @property
    def sqtp(self)->uvec4: ...

    @sqtp.setter
    def sqtp(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def sqtq(self)->uvec4: ...

    @property
    def sqps(self)->uvec4: ...

    @property
    def sqpt(self)->uvec4: ...

    @sqpt.setter
    def sqpt(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def sqpp(self)->uvec4: ...

    @property
    def sqpq(self)->uvec4: ...

    @property
    def sqqs(self)->uvec4: ...

    @property
    def sqqt(self)->uvec4: ...

    @property
    def sqqp(self)->uvec4: ...

    @property
    def sqqq(self)->uvec4: ...

    @property
    def tsss(self)->uvec4: ...

    @property
    def tsst(self)->uvec4: ...

    @property
    def tssp(self)->uvec4: ...

    @property
    def tssq(self)->uvec4: ...

    @property
    def tsts(self)->uvec4: ...

    @property
    def tstt(self)->uvec4: ...

    @property
    def tstp(self)->uvec4: ...

    @property
    def tstq(self)->uvec4: ...

    @property
    def tsps(self)->uvec4: ...

    @property
    def tspt(self)->uvec4: ...

    @property
    def tspp(self)->uvec4: ...

    @property
    def tspq(self)->uvec4: ...

    @tspq.setter
    def tspq(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def tsqs(self)->uvec4: ...

    @property
    def tsqt(self)->uvec4: ...

    @property
    def tsqp(self)->uvec4: ...

    @tsqp.setter
    def tsqp(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def tsqq(self)->uvec4: ...

    @property
    def ttss(self)->uvec4: ...

    @property
    def ttst(self)->uvec4: ...

    @property
    def ttsp(self)->uvec4: ...

    @property
    def ttsq(self)->uvec4: ...

    @property
    def ttts(self)->uvec4: ...

    @property
    def tttt(self)->uvec4: ...

    @property
    def tttp(self)->uvec4: ...

    @property
    def tttq(self)->uvec4: ...

    @property
    def ttps(self)->uvec4: ...

    @property
    def ttpt(self)->uvec4: ...

    @property
    def ttpp(self)->uvec4: ...

    @property
    def ttpq(self)->uvec4: ...

    @property
    def ttqs(self)->uvec4: ...

    @property
    def ttqt(self)->uvec4: ...

    @property
    def ttqp(self)->uvec4: ...

    @property
    def ttqq(self)->uvec4: ...

    @property
    def tpss(self)->uvec4: ...

    @property
    def tpst(self)->uvec4: ...

    @property
    def tpsp(self)->uvec4: ...

    @property
    def tpsq(self)->uvec4: ...

    @tpsq.setter
    def tpsq(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def tpts(self)->uvec4: ...

    @property
    def tptt(self)->uvec4: ...

    @property
    def tptp(self)->uvec4: ...

    @property
    def tptq(self)->uvec4: ...

    @property
    def tpps(self)->uvec4: ...

    @property
    def tppt(self)->uvec4: ...

    @property
    def tppp(self)->uvec4: ...

    @property
    def tppq(self)->uvec4: ...

    @property
    def tpqs(self)->uvec4: ...

    @tpqs.setter
    def tpqs(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def tpqt(self)->uvec4: ...

    @property
    def tpqp(self)->uvec4: ...

    @property
    def tpqq(self)->uvec4: ...

    @property
    def tqss(self)->uvec4: ...

    @property
    def tqst(self)->uvec4: ...

    @property
    def tqsp(self)->uvec4: ...

    @tqsp.setter
    def tqsp(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def tqsq(self)->uvec4: ...

    @property
    def tqts(self)->uvec4: ...

    @property
    def tqtt(self)->uvec4: ...

    @property
    def tqtp(self)->uvec4: ...

    @property
    def tqtq(self)->uvec4: ...

    @property
    def tqps(self)->uvec4: ...

    @tqps.setter
    def tqps(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def tqpt(self)->uvec4: ...

    @property
    def tqpp(self)->uvec4: ...

    @property
    def tqpq(self)->uvec4: ...

    @property
    def tqqs(self)->uvec4: ...

    @property
    def tqqt(self)->uvec4: ...

    @property
    def tqqp(self)->uvec4: ...

    @property
    def tqqq(self)->uvec4: ...

    @property
    def psss(self)->uvec4: ...

    @property
    def psst(self)->uvec4: ...

    @property
    def pssp(self)->uvec4: ...

    @property
    def pssq(self)->uvec4: ...

    @property
    def psts(self)->uvec4: ...

    @property
    def pstt(self)->uvec4: ...

    @property
    def pstp(self)->uvec4: ...

    @property
    def pstq(self)->uvec4: ...

    @pstq.setter
    def pstq(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def psps(self)->uvec4: ...

    @property
    def pspt(self)->uvec4: ...

    @property
    def pspp(self)->uvec4: ...

    @property
    def pspq(self)->uvec4: ...

    @property
    def psqs(self)->uvec4: ...

    @property
    def psqt(self)->uvec4: ...

    @psqt.setter
    def psqt(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def psqp(self)->uvec4: ...

    @property
    def psqq(self)->uvec4: ...

    @property
    def ptss(self)->uvec4: ...

    @property
    def ptst(self)->uvec4: ...

    @property
    def ptsp(self)->uvec4: ...

    @property
    def ptsq(self)->uvec4: ...

    @ptsq.setter
    def ptsq(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def ptts(self)->uvec4: ...

    @property
    def pttt(self)->uvec4: ...

    @property
    def pttp(self)->uvec4: ...

    @property
    def pttq(self)->uvec4: ...

    @property
    def ptps(self)->uvec4: ...

    @property
    def ptpt(self)->uvec4: ...

    @property
    def ptpp(self)->uvec4: ...

    @property
    def ptpq(self)->uvec4: ...

    @property
    def ptqs(self)->uvec4: ...

    @ptqs.setter
    def ptqs(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def ptqt(self)->uvec4: ...

    @property
    def ptqp(self)->uvec4: ...

    @property
    def ptqq(self)->uvec4: ...

    @property
    def ppss(self)->uvec4: ...

    @property
    def ppst(self)->uvec4: ...

    @property
    def ppsp(self)->uvec4: ...

    @property
    def ppsq(self)->uvec4: ...

    @property
    def ppts(self)->uvec4: ...

    @property
    def pptt(self)->uvec4: ...

    @property
    def pptp(self)->uvec4: ...

    @property
    def pptq(self)->uvec4: ...

    @property
    def ppps(self)->uvec4: ...

    @property
    def pppt(self)->uvec4: ...

    @property
    def pppp(self)->uvec4: ...

    @property
    def pppq(self)->uvec4: ...

    @property
    def ppqs(self)->uvec4: ...

    @property
    def ppqt(self)->uvec4: ...

    @property
    def ppqp(self)->uvec4: ...

    @property
    def ppqq(self)->uvec4: ...

    @property
    def pqss(self)->uvec4: ...

    @property
    def pqst(self)->uvec4: ...

    @pqst.setter
    def pqst(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def pqsp(self)->uvec4: ...

    @property
    def pqsq(self)->uvec4: ...

    @property
    def pqts(self)->uvec4: ...

    @pqts.setter
    def pqts(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def pqtt(self)->uvec4: ...

    @property
    def pqtp(self)->uvec4: ...

    @property
    def pqtq(self)->uvec4: ...

    @property
    def pqps(self)->uvec4: ...

    @property
    def pqpt(self)->uvec4: ...

    @property
    def pqpp(self)->uvec4: ...

    @property
    def pqpq(self)->uvec4: ...

    @property
    def pqqs(self)->uvec4: ...

    @property
    def pqqt(self)->uvec4: ...

    @property
    def pqqp(self)->uvec4: ...

    @property
    def pqqq(self)->uvec4: ...

    @property
    def qsss(self)->uvec4: ...

    @property
    def qsst(self)->uvec4: ...

    @property
    def qssp(self)->uvec4: ...

    @property
    def qssq(self)->uvec4: ...

    @property
    def qsts(self)->uvec4: ...

    @property
    def qstt(self)->uvec4: ...

    @property
    def qstp(self)->uvec4: ...

    @qstp.setter
    def qstp(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def qstq(self)->uvec4: ...

    @property
    def qsps(self)->uvec4: ...

    @property
    def qspt(self)->uvec4: ...

    @qspt.setter
    def qspt(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def qspp(self)->uvec4: ...

    @property
    def qspq(self)->uvec4: ...

    @property
    def qsqs(self)->uvec4: ...

    @property
    def qsqt(self)->uvec4: ...

    @property
    def qsqp(self)->uvec4: ...

    @property
    def qsqq(self)->uvec4: ...

    @property
    def qtss(self)->uvec4: ...

    @property
    def qtst(self)->uvec4: ...

    @property
    def qtsp(self)->uvec4: ...

    @qtsp.setter
    def qtsp(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def qtsq(self)->uvec4: ...

    @property
    def qtts(self)->uvec4: ...

    @property
    def qttt(self)->uvec4: ...

    @property
    def qttp(self)->uvec4: ...

    @property
    def qttq(self)->uvec4: ...

    @property
    def qtps(self)->uvec4: ...

    @qtps.setter
    def qtps(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def qtpt(self)->uvec4: ...

    @property
    def qtpp(self)->uvec4: ...

    @property
    def qtpq(self)->uvec4: ...

    @property
    def qtqs(self)->uvec4: ...

    @property
    def qtqt(self)->uvec4: ...

    @property
    def qtqp(self)->uvec4: ...

    @property
    def qtqq(self)->uvec4: ...

    @property
    def qpss(self)->uvec4: ...

    @property
    def qpst(self)->uvec4: ...

    @qpst.setter
    def qpst(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def qpsp(self)->uvec4: ...

    @property
    def qpsq(self)->uvec4: ...

    @property
    def qpts(self)->uvec4: ...

    @qpts.setter
    def qpts(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def qptt(self)->uvec4: ...

    @property
    def qptp(self)->uvec4: ...

    @property
    def qptq(self)->uvec4: ...

    @property
    def qpps(self)->uvec4: ...

    @property
    def qppt(self)->uvec4: ...

    @property
    def qppp(self)->uvec4: ...

    @property
    def qppq(self)->uvec4: ...

    @property
    def qpqs(self)->uvec4: ...

    @property
    def qpqt(self)->uvec4: ...

    @property
    def qpqp(self)->uvec4: ...

    @property
    def qpqq(self)->uvec4: ...

    @property
    def qqss(self)->uvec4: ...

    @property
    def qqst(self)->uvec4: ...

    @property
    def qqsp(self)->uvec4: ...

    @property
    def qqsq(self)->uvec4: ...

    @property
    def qqts(self)->uvec4: ...

    @property
    def qqtt(self)->uvec4: ...

    @property
    def qqtp(self)->uvec4: ...

    @property
    def qqtq(self)->uvec4: ...

    @property
    def qqps(self)->uvec4: ...

    @property
    def qqpt(self)->uvec4: ...

    @property
    def qqpp(self)->uvec4: ...

    @property
    def qqpq(self)->uvec4: ...

    @property
    def qqqs(self)->uvec4: ...

    @property
    def qqqt(self)->uvec4: ...

    @property
    def qqqp(self)->uvec4: ...

    @property
    def qqqq(self)->uvec4: ...
