from typing import override, Union

from .genVec2 import genVec2
from .uvec3 import uvec3
from .uvec4 import uvec4


class uvec2(genVec2):
    
    def __init__(self): ...

    @override
    def __init__(self, x:Union[bool,int,float]): ...

    @override
    def __init__(self, vec:genVec2): ...

    @override
    def __init__(self, x:Union[bool,int,float], y:Union[bool,int,float]): ...

    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->uvec2: ...

    @property
    def xy(self)->uvec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->uvec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->uvec2: ...

    @property
    def xxx(self)->uvec3: ...

    @property
    def xxy(self)->uvec3: ...

    @property
    def xyx(self)->uvec3: ...

    @property
    def xyy(self)->uvec3: ...

    @property
    def yxx(self)->uvec3: ...

    @property
    def yxy(self)->uvec3: ...

    @property
    def yyx(self)->uvec3: ...

    @property
    def yyy(self)->uvec3: ...

    @property
    def xxxx(self)->uvec4: ...

    @property
    def xxxy(self)->uvec4: ...

    @property
    def xxyx(self)->uvec4: ...

    @property
    def xxyy(self)->uvec4: ...

    @property
    def xyxx(self)->uvec4: ...

    @property
    def xyxy(self)->uvec4: ...

    @property
    def xyyx(self)->uvec4: ...

    @property
    def xyyy(self)->uvec4: ...

    @property
    def yxxx(self)->uvec4: ...

    @property
    def yxxy(self)->uvec4: ...

    @property
    def yxyx(self)->uvec4: ...

    @property
    def yxyy(self)->uvec4: ...

    @property
    def yyxx(self)->uvec4: ...

    @property
    def yyxy(self)->uvec4: ...

    @property
    def yyyx(self)->uvec4: ...

    @property
    def yyyy(self)->uvec4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->uvec2: ...

    @property
    def rg(self)->uvec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->uvec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->uvec2: ...

    @property
    def rrr(self)->uvec3: ...

    @property
    def rrg(self)->uvec3: ...

    @property
    def rgr(self)->uvec3: ...

    @property
    def rgg(self)->uvec3: ...

    @property
    def grr(self)->uvec3: ...

    @property
    def grg(self)->uvec3: ...

    @property
    def ggr(self)->uvec3: ...

    @property
    def ggg(self)->uvec3: ...

    @property
    def rrrr(self)->uvec4: ...

    @property
    def rrrg(self)->uvec4: ...

    @property
    def rrgr(self)->uvec4: ...

    @property
    def rrgg(self)->uvec4: ...

    @property
    def rgrr(self)->uvec4: ...

    @property
    def rgrg(self)->uvec4: ...

    @property
    def rggr(self)->uvec4: ...

    @property
    def rggg(self)->uvec4: ...

    @property
    def grrr(self)->uvec4: ...

    @property
    def grrg(self)->uvec4: ...

    @property
    def grgr(self)->uvec4: ...

    @property
    def grgg(self)->uvec4: ...

    @property
    def ggrr(self)->uvec4: ...

    @property
    def ggrg(self)->uvec4: ...

    @property
    def gggr(self)->uvec4: ...

    @property
    def gggg(self)->uvec4: ...

    @property
    def s(self)->int: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->int: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def ss(self)->uvec2: ...

    @property
    def st(self)->uvec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ts(self)->uvec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tt(self)->uvec2: ...

    @property
    def sss(self)->uvec3: ...

    @property
    def sst(self)->uvec3: ...

    @property
    def sts(self)->uvec3: ...

    @property
    def stt(self)->uvec3: ...

    @property
    def tss(self)->uvec3: ...

    @property
    def tst(self)->uvec3: ...

    @property
    def tts(self)->uvec3: ...

    @property
    def ttt(self)->uvec3: ...

    @property
    def ssss(self)->uvec4: ...

    @property
    def ssst(self)->uvec4: ...

    @property
    def ssts(self)->uvec4: ...

    @property
    def sstt(self)->uvec4: ...

    @property
    def stss(self)->uvec4: ...

    @property
    def stst(self)->uvec4: ...

    @property
    def stts(self)->uvec4: ...

    @property
    def sttt(self)->uvec4: ...

    @property
    def tsss(self)->uvec4: ...

    @property
    def tsst(self)->uvec4: ...

    @property
    def tsts(self)->uvec4: ...

    @property
    def tstt(self)->uvec4: ...

    @property
    def ttss(self)->uvec4: ...

    @property
    def ttst(self)->uvec4: ...

    @property
    def ttts(self)->uvec4: ...

    @property
    def tttt(self)->uvec4: ...
