from typing import override, Union

from .genVec3 import genVec3
from .genVec2 import genVec2
from .uvec2 import uvec2
from .uvec4 import uvec4


class uvec3(genVec3):
    
    def __init__(self): ...

    @override
    def __init__(self, x:Union[bool,int,float]): ...

    @override
    def __init__(self, vec:genVec3): ...

    @override
    def __init__(self, x:Union[bool,int,float], y:Union[bool,int,float], z:Union[bool,int,float]): ...

    @override
    def __init__(self, x:Union[bool,int,float], vec:genVec2): ...

    @override
    def __init__(self, vec:genVec2, z:Union[bool,int,float]): ...
    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def z(self)->int: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->uvec2: ...

    @property
    def xy(self)->uvec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xz(self)->uvec2: ...

    @xz.setter
    def xz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->uvec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->uvec2: ...

    @property
    def yz(self)->uvec2: ...

    @yz.setter
    def yz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zx(self)->uvec2: ...

    @zx.setter
    def zx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zy(self)->uvec2: ...

    @zy.setter
    def zy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zz(self)->uvec2: ...

    @property
    def xxx(self)->uvec3: ...

    @property
    def xxy(self)->uvec3: ...

    @property
    def xxz(self)->uvec3: ...

    @property
    def xyx(self)->uvec3: ...

    @property
    def xyy(self)->uvec3: ...

    @property
    def xyz(self)->uvec3: ...

    @xyz.setter
    def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzx(self)->uvec3: ...

    @property
    def xzy(self)->uvec3: ...

    @xzy.setter
    def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzz(self)->uvec3: ...

    @property
    def yxx(self)->uvec3: ...

    @property
    def yxy(self)->uvec3: ...

    @property
    def yxz(self)->uvec3: ...

    @yxz.setter
    def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yyx(self)->uvec3: ...

    @property
    def yyy(self)->uvec3: ...

    @property
    def yyz(self)->uvec3: ...

    @property
    def yzx(self)->uvec3: ...

    @yzx.setter
    def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yzy(self)->uvec3: ...

    @property
    def yzz(self)->uvec3: ...

    @property
    def zxx(self)->uvec3: ...

    @property
    def zxy(self)->uvec3: ...

    @zxy.setter
    def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zxz(self)->uvec3: ...

    @property
    def zyx(self)->uvec3: ...

    @zyx.setter
    def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyy(self)->uvec3: ...

    @property
    def zyz(self)->uvec3: ...

    @property
    def zzx(self)->uvec3: ...

    @property
    def zzy(self)->uvec3: ...

    @property
    def zzz(self)->uvec3: ...

    @property
    def xxxx(self)->uvec4: ...

    @property
    def xxxy(self)->uvec4: ...

    @property
    def xxxz(self)->uvec4: ...

    @property
    def xxyx(self)->uvec4: ...

    @property
    def xxyy(self)->uvec4: ...

    @property
    def xxyz(self)->uvec4: ...

    @property
    def xxzx(self)->uvec4: ...

    @property
    def xxzy(self)->uvec4: ...

    @property
    def xxzz(self)->uvec4: ...

    @property
    def xyxx(self)->uvec4: ...

    @property
    def xyxy(self)->uvec4: ...

    @property
    def xyxz(self)->uvec4: ...

    @property
    def xyyx(self)->uvec4: ...

    @property
    def xyyy(self)->uvec4: ...

    @property
    def xyyz(self)->uvec4: ...

    @property
    def xyzx(self)->uvec4: ...

    @property
    def xyzy(self)->uvec4: ...

    @property
    def xyzz(self)->uvec4: ...

    @property
    def xzxx(self)->uvec4: ...

    @property
    def xzxy(self)->uvec4: ...

    @property
    def xzxz(self)->uvec4: ...

    @property
    def xzyx(self)->uvec4: ...

    @property
    def xzyy(self)->uvec4: ...

    @property
    def xzyz(self)->uvec4: ...

    @property
    def xzzx(self)->uvec4: ...

    @property
    def xzzy(self)->uvec4: ...

    @property
    def xzzz(self)->uvec4: ...

    @property
    def yxxx(self)->uvec4: ...

    @property
    def yxxy(self)->uvec4: ...

    @property
    def yxxz(self)->uvec4: ...

    @property
    def yxyx(self)->uvec4: ...

    @property
    def yxyy(self)->uvec4: ...

    @property
    def yxyz(self)->uvec4: ...

    @property
    def yxzx(self)->uvec4: ...

    @property
    def yxzy(self)->uvec4: ...

    @property
    def yxzz(self)->uvec4: ...

    @property
    def yyxx(self)->uvec4: ...

    @property
    def yyxy(self)->uvec4: ...

    @property
    def yyxz(self)->uvec4: ...

    @property
    def yyyx(self)->uvec4: ...

    @property
    def yyyy(self)->uvec4: ...

    @property
    def yyyz(self)->uvec4: ...

    @property
    def yyzx(self)->uvec4: ...

    @property
    def yyzy(self)->uvec4: ...

    @property
    def yyzz(self)->uvec4: ...

    @property
    def yzxx(self)->uvec4: ...

    @property
    def yzxy(self)->uvec4: ...

    @property
    def yzxz(self)->uvec4: ...

    @property
    def yzyx(self)->uvec4: ...

    @property
    def yzyy(self)->uvec4: ...

    @property
    def yzyz(self)->uvec4: ...

    @property
    def yzzx(self)->uvec4: ...

    @property
    def yzzy(self)->uvec4: ...

    @property
    def yzzz(self)->uvec4: ...

    @property
    def zxxx(self)->uvec4: ...

    @property
    def zxxy(self)->uvec4: ...

    @property
    def zxxz(self)->uvec4: ...

    @property
    def zxyx(self)->uvec4: ...

    @property
    def zxyy(self)->uvec4: ...

    @property
    def zxyz(self)->uvec4: ...

    @property
    def zxzx(self)->uvec4: ...

    @property
    def zxzy(self)->uvec4: ...

    @property
    def zxzz(self)->uvec4: ...

    @property
    def zyxx(self)->uvec4: ...

    @property
    def zyxy(self)->uvec4: ...

    @property
    def zyxz(self)->uvec4: ...

    @property
    def zyyx(self)->uvec4: ...

    @property
    def zyyy(self)->uvec4: ...

    @property
    def zyyz(self)->uvec4: ...

    @property
    def zyzx(self)->uvec4: ...

    @property
    def zyzy(self)->uvec4: ...

    @property
    def zyzz(self)->uvec4: ...

    @property
    def zzxx(self)->uvec4: ...

    @property
    def zzxy(self)->uvec4: ...

    @property
    def zzxz(self)->uvec4: ...

    @property
    def zzyx(self)->uvec4: ...

    @property
    def zzyy(self)->uvec4: ...

    @property
    def zzyz(self)->uvec4: ...

    @property
    def zzzx(self)->uvec4: ...

    @property
    def zzzy(self)->uvec4: ...

    @property
    def zzzz(self)->uvec4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def b(self)->int: ...

    @b.setter
    def b(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->uvec2: ...

    @property
    def rg(self)->uvec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rb(self)->uvec2: ...

    @rb.setter
    def rb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->uvec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->uvec2: ...

    @property
    def gb(self)->uvec2: ...

    @gb.setter
    def gb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def br(self)->uvec2: ...

    @br.setter
    def br(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bg(self)->uvec2: ...

    @bg.setter
    def bg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bb(self)->uvec2: ...

    @property
    def rrr(self)->uvec3: ...

    @property
    def rrg(self)->uvec3: ...

    @property
    def rrb(self)->uvec3: ...

    @property
    def rgr(self)->uvec3: ...

    @property
    def rgg(self)->uvec3: ...

    @property
    def rgb(self)->uvec3: ...

    @rgb.setter
    def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbr(self)->uvec3: ...

    @property
    def rbg(self)->uvec3: ...

    @rbg.setter
    def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbb(self)->uvec3: ...

    @property
    def grr(self)->uvec3: ...

    @property
    def grg(self)->uvec3: ...

    @property
    def grb(self)->uvec3: ...

    @grb.setter
    def grb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ggr(self)->uvec3: ...

    @property
    def ggg(self)->uvec3: ...

    @property
    def ggb(self)->uvec3: ...

    @property
    def gbr(self)->uvec3: ...

    @gbr.setter
    def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gbg(self)->uvec3: ...

    @property
    def gbb(self)->uvec3: ...

    @property
    def brr(self)->uvec3: ...

    @property
    def brg(self)->uvec3: ...

    @brg.setter
    def brg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def brb(self)->uvec3: ...

    @property
    def bgr(self)->uvec3: ...

    @bgr.setter
    def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgg(self)->uvec3: ...

    @property
    def bgb(self)->uvec3: ...

    @property
    def bbr(self)->uvec3: ...

    @property
    def bbg(self)->uvec3: ...

    @property
    def bbb(self)->uvec3: ...

    @property
    def rrrr(self)->uvec4: ...

    @property
    def rrrg(self)->uvec4: ...

    @property
    def rrrb(self)->uvec4: ...

    @property
    def rrgr(self)->uvec4: ...

    @property
    def rrgg(self)->uvec4: ...

    @property
    def rrgb(self)->uvec4: ...

    @property
    def rrbr(self)->uvec4: ...

    @property
    def rrbg(self)->uvec4: ...

    @property
    def rrbb(self)->uvec4: ...

    @property
    def rgrr(self)->uvec4: ...

    @property
    def rgrg(self)->uvec4: ...

    @property
    def rgrb(self)->uvec4: ...

    @property
    def rggr(self)->uvec4: ...

    @property
    def rggg(self)->uvec4: ...

    @property
    def rggb(self)->uvec4: ...

    @property
    def rgbr(self)->uvec4: ...

    @property
    def rgbg(self)->uvec4: ...

    @property
    def rgbb(self)->uvec4: ...

    @property
    def rbrr(self)->uvec4: ...

    @property
    def rbrg(self)->uvec4: ...

    @property
    def rbrb(self)->uvec4: ...

    @property
    def rbgr(self)->uvec4: ...

    @property
    def rbgg(self)->uvec4: ...

    @property
    def rbgb(self)->uvec4: ...

    @property
    def rbbr(self)->uvec4: ...

    @property
    def rbbg(self)->uvec4: ...

    @property
    def rbbb(self)->uvec4: ...

    @property
    def grrr(self)->uvec4: ...

    @property
    def grrg(self)->uvec4: ...

    @property
    def grrb(self)->uvec4: ...

    @property
    def grgr(self)->uvec4: ...

    @property
    def grgg(self)->uvec4: ...

    @property
    def grgb(self)->uvec4: ...

    @property
    def grbr(self)->uvec4: ...

    @property
    def grbg(self)->uvec4: ...

    @property
    def grbb(self)->uvec4: ...

    @property
    def ggrr(self)->uvec4: ...

    @property
    def ggrg(self)->uvec4: ...

    @property
    def ggrb(self)->uvec4: ...

    @property
    def gggr(self)->uvec4: ...

    @property
    def gggg(self)->uvec4: ...

    @property
    def gggb(self)->uvec4: ...

    @property
    def ggbr(self)->uvec4: ...

    @property
    def ggbg(self)->uvec4: ...

    @property
    def ggbb(self)->uvec4: ...

    @property
    def gbrr(self)->uvec4: ...

    @property
    def gbrg(self)->uvec4: ...

    @property
    def gbrb(self)->uvec4: ...

    @property
    def gbgr(self)->uvec4: ...

    @property
    def gbgg(self)->uvec4: ...

    @property
    def gbgb(self)->uvec4: ...

    @property
    def gbbr(self)->uvec4: ...

    @property
    def gbbg(self)->uvec4: ...

    @property
    def gbbb(self)->uvec4: ...

    @property
    def brrr(self)->uvec4: ...

    @property
    def brrg(self)->uvec4: ...

    @property
    def brrb(self)->uvec4: ...

    @property
    def brgr(self)->uvec4: ...

    @property
    def brgg(self)->uvec4: ...

    @property
    def brgb(self)->uvec4: ...

    @property
    def brbr(self)->uvec4: ...

    @property
    def brbg(self)->uvec4: ...

    @property
    def brbb(self)->uvec4: ...

    @property
    def bgrr(self)->uvec4: ...

    @property
    def bgrg(self)->uvec4: ...

    @property
    def bgrb(self)->uvec4: ...

    @property
    def bggr(self)->uvec4: ...

    @property
    def bggg(self)->uvec4: ...

    @property
    def bggb(self)->uvec4: ...

    @property
    def bgbr(self)->uvec4: ...

    @property
    def bgbg(self)->uvec4: ...

    @property
    def bgbb(self)->uvec4: ...

    @property
    def bbrr(self)->uvec4: ...

    @property
    def bbrg(self)->uvec4: ...

    @property
    def bbrb(self)->uvec4: ...

    @property
    def bbgr(self)->uvec4: ...

    @property
    def bbgg(self)->uvec4: ...

    @property
    def bbgb(self)->uvec4: ...

    @property
    def bbbr(self)->uvec4: ...

    @property
    def bbbg(self)->uvec4: ...

    @property
    def bbbb(self)->uvec4: ...

    @property
    def s(self)->int: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->int: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def p(self)->int: ...

    @p.setter
    def p(self, value:Union[bool, int, float])->None: ...

    @property
    def ss(self)->uvec2: ...

    @property
    def st(self)->uvec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def sp(self)->uvec2: ...

    @sp.setter
    def sp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ts(self)->uvec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def tt(self)->uvec2: ...

    @property
    def tp(self)->uvec2: ...

    @tp.setter
    def tp(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ps(self)->uvec2: ...

    @ps.setter
    def ps(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def pt(self)->uvec2: ...

    @pt.setter
    def pt(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def pp(self)->uvec2: ...

    @property
    def sss(self)->uvec3: ...

    @property
    def sst(self)->uvec3: ...

    @property
    def ssp(self)->uvec3: ...

    @property
    def sts(self)->uvec3: ...

    @property
    def stt(self)->uvec3: ...

    @property
    def stp(self)->uvec3: ...

    @stp.setter
    def stp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def sps(self)->uvec3: ...

    @property
    def spt(self)->uvec3: ...

    @spt.setter
    def spt(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def spp(self)->uvec3: ...

    @property
    def tss(self)->uvec3: ...

    @property
    def tst(self)->uvec3: ...

    @property
    def tsp(self)->uvec3: ...

    @tsp.setter
    def tsp(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tts(self)->uvec3: ...

    @property
    def ttt(self)->uvec3: ...

    @property
    def ttp(self)->uvec3: ...

    @property
    def tps(self)->uvec3: ...

    @tps.setter
    def tps(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def tpt(self)->uvec3: ...

    @property
    def tpp(self)->uvec3: ...

    @property
    def pss(self)->uvec3: ...

    @property
    def pst(self)->uvec3: ...

    @pst.setter
    def pst(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def psp(self)->uvec3: ...

    @property
    def pts(self)->uvec3: ...

    @pts.setter
    def pts(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ptt(self)->uvec3: ...

    @property
    def ptp(self)->uvec3: ...

    @property
    def pps(self)->uvec3: ...

    @property
    def ppt(self)->uvec3: ...

    @property
    def ppp(self)->uvec3: ...

    @property
    def ssss(self)->uvec4: ...

    @property
    def ssst(self)->uvec4: ...

    @property
    def sssp(self)->uvec4: ...

    @property
    def ssts(self)->uvec4: ...

    @property
    def sstt(self)->uvec4: ...

    @property
    def sstp(self)->uvec4: ...

    @property
    def ssps(self)->uvec4: ...

    @property
    def sspt(self)->uvec4: ...

    @property
    def sspp(self)->uvec4: ...

    @property
    def stss(self)->uvec4: ...

    @property
    def stst(self)->uvec4: ...

    @property
    def stsp(self)->uvec4: ...

    @property
    def stts(self)->uvec4: ...

    @property
    def sttt(self)->uvec4: ...

    @property
    def sttp(self)->uvec4: ...

    @property
    def stps(self)->uvec4: ...

    @property
    def stpt(self)->uvec4: ...

    @property
    def stpp(self)->uvec4: ...

    @property
    def spss(self)->uvec4: ...

    @property
    def spst(self)->uvec4: ...

    @property
    def spsp(self)->uvec4: ...

    @property
    def spts(self)->uvec4: ...

    @property
    def sptt(self)->uvec4: ...

    @property
    def sptp(self)->uvec4: ...

    @property
    def spps(self)->uvec4: ...

    @property
    def sppt(self)->uvec4: ...

    @property
    def sppp(self)->uvec4: ...

    @property
    def tsss(self)->uvec4: ...

    @property
    def tsst(self)->uvec4: ...

    @property
    def tssp(self)->uvec4: ...

    @property
    def tsts(self)->uvec4: ...

    @property
    def tstt(self)->uvec4: ...

    @property
    def tstp(self)->uvec4: ...

    @property
    def tsps(self)->uvec4: ...

    @property
    def tspt(self)->uvec4: ...

    @property
    def tspp(self)->uvec4: ...

    @property
    def ttss(self)->uvec4: ...

    @property
    def ttst(self)->uvec4: ...

    @property
    def ttsp(self)->uvec4: ...

    @property
    def ttts(self)->uvec4: ...

    @property
    def tttt(self)->uvec4: ...

    @property
    def tttp(self)->uvec4: ...

    @property
    def ttps(self)->uvec4: ...

    @property
    def ttpt(self)->uvec4: ...

    @property
    def ttpp(self)->uvec4: ...

    @property
    def tpss(self)->uvec4: ...

    @property
    def tpst(self)->uvec4: ...

    @property
    def tpsp(self)->uvec4: ...

    @property
    def tpts(self)->uvec4: ...

    @property
    def tptt(self)->uvec4: ...

    @property
    def tptp(self)->uvec4: ...

    @property
    def tpps(self)->uvec4: ...

    @property
    def tppt(self)->uvec4: ...

    @property
    def tppp(self)->uvec4: ...

    @property
    def psss(self)->uvec4: ...

    @property
    def psst(self)->uvec4: ...

    @property
    def pssp(self)->uvec4: ...

    @property
    def psts(self)->uvec4: ...

    @property
    def pstt(self)->uvec4: ...

    @property
    def pstp(self)->uvec4: ...

    @property
    def psps(self)->uvec4: ...

    @property
    def pspt(self)->uvec4: ...

    @property
    def pspp(self)->uvec4: ...

    @property
    def ptss(self)->uvec4: ...

    @property
    def ptst(self)->uvec4: ...

    @property
    def ptsp(self)->uvec4: ...

    @property
    def ptts(self)->uvec4: ...

    @property
    def pttt(self)->uvec4: ...

    @property
    def pttp(self)->uvec4: ...

    @property
    def ptps(self)->uvec4: ...

    @property
    def ptpt(self)->uvec4: ...

    @property
    def ptpp(self)->uvec4: ...

    @property
    def ppss(self)->uvec4: ...

    @property
    def ppst(self)->uvec4: ...

    @property
    def ppsp(self)->uvec4: ...

    @property
    def ppts(self)->uvec4: ...

    @property
    def pptt(self)->uvec4: ...

    @property
    def pptp(self)->uvec4: ...

    @property
    def ppps(self)->uvec4: ...

    @property
    def pppt(self)->uvec4: ...

    @property
    def pppp(self)->uvec4: ...
