
    @property
    def rrrr(self)->vec4: ...

    @property
    def x(self)->float: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def grrg(self)->vec4: ...

    @property
    def rgrr(self)->vec4: ...

    @property
    def tt(self)->vec2: ...

    @property
    def rrgr(self)->vec4: ...

    @property
    def grgr(self)->vec4: ...

    @property
    def yxyx(self)->vec4: ...

    @property
    def yyx(self)->vec3: ...

    @property
    def yxxx(self)->vec4: ...

    @property
    def g(self)->float: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def t(self)->float: ...

    @t.setter
    def t(self, value:Union[bool, int, float])->None: ...

    @property
    def grg(self)->vec3: ...

    @property
    def xxyx(self)->vec4: ...

    @property
    def ggg(self)->vec3: ...

    @property
    def ggrr(self)->vec4: ...

    @property
    def yyyx(self)->vec4: ...

    @property
    def tsss(self)->vec4: ...

    @property
    def tsst(self)->vec4: ...

    @property
    def yxy(self)->vec3: ...

    @property
    def ggr(self)->vec3: ...

    @property
    def stt(self)->vec3: ...

    @property
    def tttt(self)->vec4: ...

    @property
    def gr(self)->vec2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->vec2: ...

    @property
    def sttt(self)->vec4: ...

    @property
    def ttss(self)->vec4: ...

    @property
    def stst(self)->vec4: ...

    @property
    def ssss(self)->vec4: ...

    @property
    def rrgg(self)->vec4: ...

    @property
    def yxxy(self)->vec4: ...

    @property
    def yy(self)->vec2: ...

    @property
    def ts(self)->vec2: ...

    @ts.setter
    def ts(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rrr(self)->vec3: ...

    @property
    def tss(self)->vec3: ...

    @property
    def yyxx(self)->vec4: ...

    @property
    def y(self)->float: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xxxx(self)->vec4: ...

    @property
    def xyxx(self)->vec4: ...

    @property
    def rgr(self)->vec3: ...

    @property
    def xxy(self)->vec3: ...

    @property
    def xyyx(self)->vec4: ...

    @property
    def rrrg(self)->vec4: ...

    @property
    def xyxy(self)->vec4: ...

    @property
    def r(self)->float: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def rgrg(self)->vec4: ...

    @property
    def ss(self)->vec2: ...

    @property
    def grgg(self)->vec4: ...

    @property
    def xxxy(self)->vec4: ...

    @property
    def yyy(self)->vec3: ...

    @property
    def gggr(self)->vec4: ...

    @property
    def yyyy(self)->vec4: ...

    @property
    def st(self)->vec2: ...

    @st.setter
    def st(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yxyy(self)->vec4: ...

    @property
    def xyy(self)->vec3: ...

    @property
    def ttt(self)->vec3: ...

    @property
    def rrg(self)->vec3: ...

    @property
    def tstt(self)->vec4: ...

    @property
    def xx(self)->vec2: ...

    @property
    def sts(self)->vec3: ...

    @property
    def ttts(self)->vec4: ...

    @property
    def ggrg(self)->vec4: ...

    @property
    def stts(self)->vec4: ...

    @property
    def ssts(self)->vec4: ...

    @property
    def rgg(self)->vec3: ...

    @property
    def xxyy(self)->vec4: ...

    @property
    def gggg(self)->vec4: ...

    @property
    def tst(self)->vec3: ...

    @property
    def rg(self)->vec2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rggr(self)->vec4: ...

    @property
    def rggg(self)->vec4: ...

    @property
    def stss(self)->vec4: ...

    @property
    def xxx(self)->vec3: ...

    @property
    def sstt(self)->vec4: ...

    @property
    def xy(self)->vec2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rr(self)->vec2: ...

    @property
    def ttst(self)->vec4: ...

    @property
    def yxx(self)->vec3: ...

    @property
    def grrr(self)->vec4: ...

    @property
    def tts(self)->vec3: ...

    @property
    def xyyy(self)->vec4: ...

    @property
    def xyx(self)->vec3: ...

    @property
    def ssst(self)->vec4: ...

    @property
    def tsts(self)->vec4: ...

    @property
    def grr(self)->vec3: ...

    @property
    def yyxy(self)->vec4: ...

    @property
    def yx(self)->vec2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s(self)->float: ...

    @s.setter
    def s(self, value:Union[bool, int, float])->None: ...

    @property
    def sss(self)->vec3: ...

    @property
    def sst(self)->vec3: ...
